### ISSUE TITLE
Support for Lainchan's /mega/ board

### ISSUE THREAD

**Issue by JordanRobinson** [Mishiranu/Dashchan#100]
Hello, I wasn't sure whether to put this here or on the extensions page, so sorry if I've put it in the wrong place.

Lainchan recently added some new boards, such as /mega/, which displays the threads from all boards, in bump order. This is pretty cool, but it doesn't work in dashchan.

It looks to me as though the reason is because the json returned by /mega/ is subtly different.

Please see attachment for details of a comparison of a normal Lainchan board on the left, and /mega/ on the right.

I haven't dug too much into the code myself, but I figure there might also be a problem in terms of the app trying to link to the threads as if they are a part of the mega board directly (The threads still live under each respective board, /lam/ /civ/ etc).

Let me know if you need any more details.

Thanks.

![lainchan-json-differences](https://cloud.githubusercontent.com/assets/1202911/20465109/bd0d3eee-af4d-11e6-8a16-1d9fb2b01bb8.jpg)

**Comment by Mishiranu** [comment]
There are some problems. This board has only 1 page and the rest pages are loaded from HTML from other boards. So this board is not so functional as you can think.
The second problem is API. I can't extract a board code from server response, so I don't know which thread I must show to user.
