### ISSUE TITLE
[2ch] Отключить проверку сертификата на джваче

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#101]
Опция в программе отключает что? На двач это не распространяется.

**Comment by Mishiranu** [comment]
Распространяется на всё.

**Comment by ololoe** [comment]
Когда я последний раз проверял фиддлером - не распространялось. Как руки дойдут проверю, можешь и сам проверить.

**Comment by Mishiranu** [comment]
Ну что проверять-то, либо эта опция вообще не работает, либо работает везде для всех имиджборд, третьего варианта нет. И, сколько я помню, опция всегда работала корректно. Если проверишь и окажется, что не работет — напиши снова.

**Comment by ololoe** [comment]
Может быть нигде и не работала. Сейчас заработала.

**Comment by Mishiranu** [comment]
> можно в описание добавить "опасно!" или "не рекомендуется!"

Я думаю, те, кто беспокоятся о безопасности в сети, сами понимают, зачем нужна эта галочка. А остальные и так снимут, независимо от того, что написано.

**Comment by ololoe** [comment]
Ну это большой вопрос. По моему опыту, желающих принимать невалидные сертификаты в браузере стало гораздо меньше после того как в фаерфоксе это стало сделать сложнее чем нажать одну кнопку. Но дело твое.
