### ISSUE TITLE
Blank thumbnails in most threads

### ISSUE THREAD

**Issue by Akka47** [Mishiranu/Dashchan#104]
I'm on 2.9.0 running Android 7.1 and I can't see almost any thumbnail, happening in 4chan, lainchan and 420chan (possible to affect all of them). Am I doing something wrong?

Screenshots:
https://my.mixtape.moe/xnqpzg.png
https://my.mixtape.moe/nrgidz.png
https://my.mixtape.moe/cbmigu.png
https://my.mixtape.moe/gsvbge.png

**Comment by Mishiranu** [comment]
That's strange. In next version thumbnail system will be greatly refactored, so then we can make some tests to figure out a reason of this problem.

Are you sure you have thumbnails loading enabled in settings?

**Comment by Akka47** [comment]
Wow, I can't believe I'm saying this but you're right, I had thumbnail loading set in 'Never'. I feel really stupid right now, sorry for wasting your time!
