### ISSUE TITLE
Enlarge all image in thread

### ISSUE THREAD

**Issue by anhchuong95** [Mishiranu/Dashchan#107]
I'd love to flick through the thread with all the enlarged image following by the post. Could it be done somehow in dashchan? 
Definitely a great feature for someone who don't like the hassle as to browse through gallery and tap "Go to post" to see the comment.

**Comment by Mishiranu** [comment]
You can change thumbnal scale in Preferences — Interface — Thumbnail scale. Is it what you wanted?

**Comment by anhchuong95** [comment]
Thanks for your quick reply. What I meant is the full image, not the thumbnail.

**Comment by ApertureAndroid** [comment]
Preferences -> Interface -> Scroll thread when scrolling gallery
Enable that and whenever you go into the apps gallery mode and scroll, it'll also take you to the post that the image is from. Just exit out of the image and you'll see the post.

**Comment by anhchuong95** [comment]
Sorry that I had not stated it clearly. I just want to flick through the thread with full image preloading without have to tap to the thumbnail to view the full image. 
It is really painful to view low resolution of the thumbnail in the image board, don't you think?

**Comment by Mishiranu** [comment]
I don't think it's realizable. It's a completely new UI with different behavior.
