### ISSUE TITLE
Crashes when clicking a youtube thumbnail from an Opening Post

### ISSUE THREAD

**Issue by iiiGerardoiii** [Mishiranu/Dashchan#11]
If you spot a thread where the Opening Post contains a youtube thumbnail instead of a conventional image, and click on it, the app will crash. This happens on 8ch. I haven't tried to reproduce this problem on other imageboards tho.

**Comment by Mishiranu** [comment]
Check this error on a latest client and extension versions. Maybe it'll work correctly.

**Comment by iiiGerardoiii** [comment]
yup, I had an old version my bad.
