### ISSUE TITLE
Highlighting the bottom post of a threads crashes the app

### ISSUE THREAD

**Issue by waltrg** [Mishiranu/Dashchan#112]
Device: HTC 10, Android 7.0

If I try to double tap the bottom/last post of a thread to select its text, the app crashes sometimes.

**Comment by Mishiranu** [comment]
Selection method was completely refactored in https://github.com/Mishiranu/Dashchan/commit/2148db58c31a572a061f6b645c97cb717c5c552b but hasn't released yet. I think now it won't crash but I don't sure selection will work. At least on MIUI it doesn't. If you want, I can build a testing APK for you or you can do it yourself.
