### ISSUE TITLE
can't upload any files for 8ch.net

### ISSUE THREAD

**Issue by tostepp** [Mishiranu/Dashchan#113]
Every time I try attaching an image/video to a post, a message just pops up, reading "invalid server response". There are no other connection issues, I can make text only posts, I can attach files to posts on other extensions, and I tried changing image settings. It only happened after getting the latest patch.

I'm on a motorola xoom.

**Comment by Mishiranu** [comment]
Something was changed in their posting system. Now they have 2 `post.php` scripts on different domains and one of them is broken when you try to upload a file.

I released a new version of extension, it should work.

**Comment by tostepp** [comment]
Thanks! You're really quick.
