### ISSUE TITLE
8chan Redtext Rendering

### ISSUE THREAD

**Issue by diyasteng** [Mishiranu/Dashchan#115]
Redtexts do not render in the app. Tried doing it, it looks fine in a browser but doesnt render in dashchan, just looks like plain text.

**Comment by Mishiranu** [comment]
Red text is rendered with different font size and family if you mean == tag.

**Comment by diyasteng** [comment]
yes i mean ==. i tried it with dashchan, thread just shows plain text in dashchan instead of redtext. opened the same thread in a browser and my redtext shows normally.

**Comment by Mishiranu** [comment]
Can you provide a screenshot please?

**Comment by diyasteng** [comment]
![screenshot_20170224-193837](https://cloud.githubusercontent.com/assets/22583094/23302641/6f1f1b62-faca-11e6-87ad-67f9565aee5e.png)
![screenshot_20170224-193859](https://cloud.githubusercontent.com/assets/22583094/23302643/712baaa6-faca-11e6-80f2-830ce67cbb34.png)
![screenshot_20170224-194001](https://cloud.githubusercontent.com/assets/22583094/23302644/726f7c3a-faca-11e6-8f52-b533e3e62657.png)

**Comment by Mishiranu** [comment]
> Red text is rendered with different font size and family

**Comment by diyasteng** [comment]
meaning?

**Comment by Mishiranu** [comment]
The font is larger and thinner. Try to post header with normal text and you'll tell the difference.

**Comment by diyasteng** [comment]
but it doesnt show it with red color in the app though?

**Comment by Mishiranu** [comment]
No. Only like a header.
I do not want to change the color.

**Comment by diyasteng** [comment]
Thanks, that cleared that up. i thought it was a bug.
