### ISSUE TITLE
Загрузка тредов в многопотоке

### ISSUE THREAD

**Issue by schvabodka-man** [Mishiranu/Dashchan#116]
Привет! После долгого юзания дешчана заметил что открытые треды не грузятся в бекграунде(т.е в случае если медленный Интернет открыть несколько тредов, открыть один из них то остальные просто не будут грузится). Было бы неплохо реализовать фоновую загрузку тредов которые неоткрыты и висят в бекграунде.

**Comment by Mishiranu** [comment]
Вообще сначала подумал о фоновом обновлении тредов, но это немного другое. Я думаю, когда-нибудь сделаю фоновое обновление избранных тредов, тогда можно будет попробовать реализовать то, что ты хочешь, поскольку эти задачи имеют связь.
