### ISSUE TITLE
Lainchan submissions are always spoilered

### ISSUE THREAD

**Issue by waltrg** [Mishiranu/Dashchan#117]
Hey, I found a small issue with the Lainchan extension.  

Scenario: 
1. Make post with image 
2. Submit

Result: 
Image is spoilered no matter what. 

Device:
HTC 10, Android 7.0, Dashchan v2.9.0, Extension v1.3

Regardless, thanks for working on this great app!

**Comment by Mishiranu** [comment]
Fixed.

**Comment by waltrg** [comment]
<3
