### ISSUE TITLE
Unable to create posts in 4chan

### ISSUE THREAD

**Issue by Lukethehedgehog** [Mishiranu/Dashchan#118]
If I use the old captcha, no matter how many times I input it, it tells me "Captcha is not valid", and when I use Captcha 2 (Where you have to click squares), most of the time it doesn't even load.

**Comment by Mishiranu** [comment]
The recaptcha 1 doesn't work when you try to create a new thread, only recaptcha 2 works. So I've updated the extension to use the second captcha on new threads.

Recaptcha 2 is broken in last client release so you should disable javascript to use it.
