### ISSUE TITLE
Issue in posting in 4chan using reCAPTCHA v2

### ISSUE THREAD

**Issue by migzzzz** [Mishiranu/Dashchan#119]
I noticed a few days ago that I was having issues with the captcha.

I was using reCAPTCHA v2 but kept getting the "invalid captcha error" even though I already **unchecked** the  "Use Javascript for reCAPTCHA".

The only way I was able to post again was to change the CAPTCHA to v1. 

Am I missing something to not be able to use reCAPTCHA v2 properly?

**Comment by Mishiranu** [comment]
reCAPTCHA v2 was changed and it requires some proper headers now. I fixed it for CloudFlare but I don't know how to embed this fix to extensions properly. I'll try to fix it to next update.

**Comment by migzzzz** [comment]
Understood. Thank you for the response. I thought I messed with the settings or something.
