### ISSUE TITLE
App crashes if gallery opened before thread loaded

### ISSUE THREAD

**Issue by CuteGridView** [Mishiranu/Dashchan#12]
Version:
App: 2.2.0 (03.09.2015)
4chan extension: 1.1

STEPS_TO_REPRODUCE:
1. Открыть тред.
2. Открыть галерею до того как содержимое треда загрузится.
3. В приложении "Dashchan" произошла ошибка.

Воспроизводится стабильно, желательно открывать большой тред.

**Comment by Mishiranu** [comment]
Да, вижу. Исправлю.

Пока просто не надо открывать галерею, пока тред не загрузится (всё равно там будет написано, что галерея пуста).
