### ISSUE TITLE
8chan extension 403 Forbidden

### ISSUE THREAD

**Issue by fidelt** [Mishiranu/Dashchan#122]
Unable to access 8chan. Maybe due to the security fixes recently implemented?
Visiting results in 403 Forbidden.

**Comment by InstallGentoo11** [comment]
Same here.

**Comment by Mishiranu** [comment]
They've banned a lot of scripts like settings.php or search.php which are required by extension to work properly.

Maybe you can ask administrators about that? It doesn't seem to be security fix.

**Comment by Cipherwraith** [comment]
Some scripts are still being audited and will come back online as we check them. Sorry for that.

**Comment by Mishiranu** [comment]
Seems fixed.
