### ISSUE TITLE
Количество непрочитанных сообщений уходит в минус

### ISSUE THREAD

**Issue by schvabodka-man** [Mishiranu/Dashchan#124]
Привет. По каким-то непонятным причинам после "подписки" на тред, количество непрочитанных сообщений в нем уходит в минусовое и все время снижается. Если открыть тред то количество непрочитанных будет уже равно нулю, но как только оно рефрешнится оно опять уйдет в минуса. И так происходит почти с каждым тредом.
Выглядит это вот так
https://transfer.sh/YrKjR/Screenshot_20170412-190540.png
Девайс - нексус 5х
Даш версии 2.9.0
Двачеплагин 1.32

**Comment by devarped** [comment]
Уже тысячу раз поднимали эту тему. Счётчик уходит в минус тогда, когда в треде удаляются посты.

**Comment by Mishiranu** [comment]
Об этом в треде в FAQ также написано.
