### ISSUE TITLE
Show reply count in Gallery Mode

### ISSUE THREAD

**Issue by iiiGerardoiii** [Mishiranu/Dashchan#125]
An option to add a reply count on the gallery would be nice. This feature would be very useful in /gif/ or /wsg/ threads as it gives a hint of how dank the file is before playing it.

Something like this maybe?:
![screenshot_2017-04-16-03-43-51](https://cloud.githubusercontent.com/assets/6264194/25071070/daaedb94-2273-11e7-8103-24a67a14a317.png)

**Comment by Mishiranu** [comment]
Thanks for the graphics, but thb I don't think this counter may be related to gallery. The gallery is separated from navigator and I think such information shouldn't be there.
