### ISSUE TITLE
"Unable to download data" after solving captcha

### ISSUE THREAD

**Issue by rumrumrum** [Mishiranu/Dashchan#126]
I can't post on 4chan. After resolving captcha I get the abovementioned notification.

I was wandering if it's due to using cerberus

**Comment by Mishiranu** [comment]
That's a known issue. reCAPTCHA 2 with JS is broken and never be fixed. Next version won't support it, so I recommend to switch to old reCAPTCHA for posting (threads will require reCAPTCHA 2 as before but without JS so it will be a bit harder).
