### ISSUE TITLE
Archivers won't load threads? 

### ISSUE THREAD

**Issue by johnledezma34** [Mishiranu/Dashchan#129]
4plebs.org:------When I load the catalog at /HR/ for example I'm able to load it, and clicking on the preview works, but when i click at a post it displays nothing except for "this thread doesn't exist". 
This happens the same for other archives but they wont even load the catalog like asia.rbt

**Comment by johnledezma34** [comment]
![screenshot_20170502-185649](https://cloud.githubusercontent.com/assets/15113074/25644224/f9496e04-2f69-11e7-87dd-a2d3122c7741.png)
![screenshot_20170502-185643](https://cloud.githubusercontent.com/assets/15113074/25644221/f9475632-2f69-11e7-81d8-960c17f46ae1.png)
![screenshot_20170502-185634](https://cloud.githubusercontent.com/assets/15113074/25644223/f948bf90-2f69-11e7-8094-7323c72f25f5.png)
![screenshot_20170502-185631](https://cloud.githubusercontent.com/assets/15113074/25644220/f9463d2e-2f69-11e7-934c-2f157a17d388.png)
![screenshot_20170502-185654](https://cloud.githubusercontent.com/assets/15113074/25644222/f9481356-2f69-11e7-9b5d-d064f29b5fcc.png)

**Comment by Mishiranu** [comment]
4plebs is broken.
rbt has foolfuuka and need to be rewritten.

**Comment by johnledezma34** [comment]
OK Thanks, here's the log if it's nay help Mishiranu 
[log-1493770466890.txt.txt](https://github.com/Mishiranu/Dashchan/files/972247/log-1493770466890.txt.txt)
