### ISSUE TITLE
На MIUI не выделяется текст

### ISSUE THREAD

**Issue by megapro17** [Mishiranu/Dashchan#132]
При нажатии дабл тапом на текст он выделяется на пол секунды, а потом выделение продает, и кнопки не появляются. Раньше все работало корректно.

**Comment by Mishiranu** [comment]
В следующей версии должно заработать.
А ещё начиная с какого-то обновления MIUI было введено изменение, которое вообще никак не позволит теперь выделению работать. Если со следующим обновлением клиента не заработает, то уже вряд ли больше будет работать.
