### ISSUE TITLE
27chan extension 

### ISSUE THREAD

**Issue by Tsv33** [Mishiranu/Dashchan#134]
Would it be possible to add support for http://27chan.org to dashchan?
The imageboard makes use of vichan.

**Comment by 4lch3-m1st** [comment]
I managed to create an extension for 27chan, as reported in the /enter/ board.
I'm going to submit the code on the proper repo so @Mishiranu can take a look.

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan-Extensions/raw/master/update/package/DashchanTwentySeven.apk
