### ISSUE TITLE
Отправлять сообщения в фоне по умолчанию

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#135]
Заодно можно будет легко прикрутить решалки капч.

Еще стоит сделать возможность писать второе сообщение пока не отправилось первое.

**Comment by Mishiranu** [comment]
Как правило, если при отправке происходит ошибка, ты о ней сразу узнаёшь. Если сделать автоматическое сворачивание, то будут прыжки окошек. Мне это не нравится.

Одновременно писать второе сообщение тоже нельзя. Ситуация следующая: ты отправляешь сообщение с большим файлом, сворачиваешь, начинаешь писать новое сообщение. Вдруг выясняется, что при отправке первого сообщения произошла ошибка, и нужно отобразить его снова. Возникает конфликт: сейчас ты уже пишешь новое сообщение, это новый черновик, а тебе на его место приходит старое сообщение. Получается, нужна какая-то расширенная поддержка черновиков, позволяющая одновременно для одного треда держать больше 1 неотправленного сообщения и переключаться между этими сообщениями.

Довольно сложная задача, нужная всего лишь ради отправки двух постов одновременно. Я считаю, что это не нужно.

**Comment by ololoe** [comment]
Ну хз, я когда отправляю сразу быстро жму "свернуть" тк у меня двач лагает. Прыжки окошек раз в год для меня лучше ожидания в несколько секунд каждый раз. Можно сделать опцией.
