### ISSUE TITLE
Глюк гуя

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#136]
Если быстро два раза нажать на ссылку на ответ пока он открывается, то он откроется 2 раза. Поставь и проверяй флаг, что ли.

**Comment by Mishiranu** [comment]
Это известная проблема, вообще присущая всему андроиду. В любом, даже системном приложении, можно обнаружить подобные баги, пытаясь быстро ткнуть по кнопке или разным кнопкам.
А починить это нифига не просто, потому что этот баг не в конкретном одном месте, он везде, и чинить его также нужно везде. Я этим просто не вижу смысла заниматься.

**Comment by ololoe** [comment]
А на десктопе таких проблем нет?

**Comment by Mishiranu** [comment]
А при чём здесь десктоп?

**Comment by ololoe** [comment]
> Это известная проблема, вообще присущая всему андроиду. 

А не на андроиде они есть?

**Comment by Mishiranu** [comment]
Понятия не имею. Сильно зависит от того, как это реализовано на уровне используемого фреймворка/тулкита.

**Comment by ololoe** [comment]
Просто я про такие приколы первый раз слышу. Значит, на десктопе это как-то решается.

**Comment by Mishiranu** [comment]
Сколько помню, с первых версий ведра так было. И, я полагаю, что не только на ведре так.
Всё просто: между нажатием на кнопку и отображением окна происходят некоторые изменения в процессе менеджера окон и связанных с ним, во время которых приложение продолжает работать и реагировать на нажатия. Поэтому можно успеть нажать два раза.

В десктопных приложениях обычно сразу за нажатием следует отображение окна, на одном шаге обработки очереди сообщений.

**Comment by ololoe** [comment]
А проверять флаги или делать локи разрабы андроида/приложений не научились?

**Comment by Mishiranu** [comment]
Ты предлагаешь для каждого нажимаемого элемента (чьё нажатие может контролироваться даже не собственноручно) блокировать нажатие, а по осуществлению нужного действия снимать блокировку? Удивительно простое дело, почему никто раньше не додумался?

**Comment by ololoe** [comment]
Я предлагаю перенять опыт десктопа и указываю на то, что решение вполне себе существует, было бы желание. Баг вроде бы и не смертельный, просто показывает какую-то детскую кривизну, как когда школьник сел за студию и что-то склепал. Выглядит как взрослая программа, но только если не тыкать куда не надо - а то глючить начнет или свалится.

**Comment by Mishiranu** [comment]
Можно вообще отказаться от многих возможностей фреймворка и нативно реализовать свою отрисовку окон и обработку событий. Всего-то нехватает, как ты говоришь, желания, верно?

Но если ограничиться _разумными_ рамками, делая всё в рамках предоставляемого фреймворка андроида и не используются огромные чудовищные костыли, которые способны _покрыть все возможные ситуации_, то решения _не существует_.

**Comment by ololoe** [comment]
Ну я не пишу про тебя лично а больше про ситуацию когда проявляются откровенно детские баги. Я не знаком с андроидом настолько чтобы сказать у кого косяк - у тебя или в гуй фреймверке у самого андроида. Но должен сказать, что эту проблему я находил только в дашчане.
