### ISSUE TITLE
Сохранение файлов

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#137]
Если файл существует: "сохранить все" я бы назвал "переименовать"

**Comment by Mishiranu** [comment]
А есть смысл? Как-то не вижу особой разницы.

**Comment by ololoe** [comment]
О чем говорит "сохранить все"? Заменять без предупреждения?

**Comment by Mishiranu** [comment]
А о чём говорит «переименовать»? Переименовать новый файл или старый?
Ну серьёзно, это совсем мелочь какая-то и максимально внятно объяснить в таком маленьком диалоговом окошке как-то не выйдет, всегда вопросы могут остаться.

**Comment by ololoe** [comment]
Диалог сохранения чего? Новых или старых файлов?
Файловые менеджеры вроде ТК или фара как то диалоги выдают и все понятно.

**Comment by Mishiranu** [comment]
> Диалог сохранения чего? Новых или старых файлов?
Каким образом это что-то меняет?

> Файловые менеджеры вроде ТК или фара как то диалоги выдают и все понятно.
Да и «сохранить все» довольно таки понятно, лол.

**Comment by ololoe** [comment]
Диалог сохранения новых файлов, соответственно все что в нем написано относится к ним.

> Да и «сохранить все» довольно таки понятно, лол.

Сохранить как? С заменой или без?

**Comment by Mishiranu** [comment]
> Диалог сохранения новых файлов, соответственно все что в нем написано относится к ним.

Это ничем не ганартируется.

> Сохранить как? С заменой или без?

Ты предлагаешь по кругу наш диалог запустить?
Кстати, для замены есть отдельный пункт, наличие которого также даёт предположить, что этот пункт таки не заменяет. Иначе зачем два одинаковых пункта?

**Comment by ololoe** [comment]
Блин, сохраняются новые файлы, поэтому вылазящий запрос (заменить/не заменять/переименовать), очевидно, относится к ним - заменять старые новыми итд.

> Иначе зачем два одинаковых пункта?

Ты предлагаешь пользователю угадывать, не кран ли автор? Не проще ли назвать соответствующе?

Ну вот тотал коммандер при копировании, если файл с таким именем уже есть, предлагает вариант "заменить". Вроде понятно, что имеется в виду. А представь себе, там бы вместо этого был вариант "сохранить все"?

**Comment by Mishiranu** [comment]
Почему ты так привязался к файловому менеджеру? Подобные вопросы он задаёт при попытке переместить/скопировать _существующие_ файлы. Дашчан _создаёт_ новые файлы, технически ему нечего _переименовывать_. Твоя аналогия с файловым менеджером инвалид.

> Блин, сохраняются новые файлы, поэтому вылазящий запрос (заменить/не заменять/переименовать), очевидно, относится к ним - заменять старые новыми итд.

Не вижу ничего здесь очевидного. Дашчан с тем же успехом может переименовывать и существующие файлы, ничто его не ограничивает. А ведь он так и пишет: «файл уже существует». Вполне ожидаемо, что «переименовать» может действовать на существующий файл. И вот тут нет абсолютно никих способов сделать верное логическое заключение, кроме как вручную проверить, что же на самом деле будет.

А каким образом фраза «сохранить _все_» может подразумевать «ну на самом деле _не все_, файлы будут заменены» я тоже не понимаю.

> Ты предлагаешь пользователю угадывать, не кран ли автор?

Я полагаю, что пользователь не дурак и очень легко сообразит, что делает пункт «сохранить все», и даже если это ему вдруг покажется неочевидным изначально (за столько времени ни у кого проблем с этим не возникало), он сможет догадаться по наличию действительного пункта, который делает замену, и который, кстати, выбран по умолчанию.

В общем, я свою позицию высказал, менять просто так я не вижу никакого смысла.

**Comment by ololoe** [comment]
> Почему ты так привязался к файловому менеджеру?
У тебя есть другие примеры?

>А каким образом фраза «сохранить все» может подразумевать «ну на самом деле не все, файлы будут заменены» я тоже не понимаю.
Она не гарантирует, что они не будут заменены (она же не говорит, как именно сохранить), а в таком случае мне лично стремно нажимать "да".

Смотреть на другие пункты чтобы понять что делает этот пункт не комильфо, как я думаю.

> Не вижу ничего здесь очевидного. Дашчан с тем же успехом может переименовывать и существующие файлы, ничто его не ограничивает. А ведь он так и пишет: «файл уже существует». Вполне ожидаемо, что «переименовать» может действовать на существующий файл. И вот тут нет абсолютно никих способов сделать верное логическое заключение, кроме как вручную проверить, что же на самом деле будет.

Уфф. Устал я :) Надо народ спросить.
