### ISSUE TITLE
Слетают пометки "мой пост"

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#138]
Иногда слетают, иногда держатся. все сложно, короч.

**Comment by Mishiranu** [comment]
Тебе ещё не удалось выяснить, при каких действиях такое происходит?

**Comment by ololoe** [comment]
Нет. Только что проапгрейдил плагин с полным перезапуском - отметка выжила.

**Comment by ololoe** [comment]
Есть какие-то идеи как это расследовать?

**Comment by Mishiranu** [comment]
Ну я попозже сделаю логгирование в некоторых местах и скину пакет сюда чтобы в случае чего по логам понять можно было.

Кстати, когда пометки слетают, ты получаешь сообщение о новых сообщениях в треде при заходе в тред? Или все сообщения как непрочитанные даже помечаются?
