### ISSUE TITLE
DashChan EndChan Embed Issue 

### ISSUE THREAD

**Issue by IWillRedPillYou** [Mishiranu/Dashchan#139]
First thank you for updating the EndChan extension you're awesome.

Secondly on EndChan we allow youtube embeds via bbcode [youtube] ID here [/youtube] 

However when using Dashchan it manually reroutes to the YouTube application when trying to play an embedded video. This is not good for many of us who do not use Google products.

Here's the thread about EndChan's embed system. Maybe you can find a work around? 
https://www.endchan.xyz/operate/res/5106.html

Thx

**Comment by devarped** [comment]
I don't think that adding an option to play embeds in the app is good idea. That would just bloat it. 
How about using [NewPipe](https://github.com/TeamNewPipe/NewPipe)?

**Comment by IWillRedPillYou** [comment]
I'll try that thanks again

**Comment by IWillRedPillYou** [comment]
Actually I'm not a programmer lol can is there an Apk I can simply install **sorry for being a newfaggot chick**

**Comment by IWillRedPillYou** [comment]
Nevermind found it 
http://www.apkmirror.com/apk/thescrabi/newpipe/newpipe-0-9-7-release/newpipe-0-9-7-android-apk-download/

**Comment by Mishiranu** [comment]
Dashchan can't play YouTube videos and won't. When you click on this link, Dashchan reroutes it to the app which can open `https://youtube.com/…` links and YouTube app is one of them. But it isn't required, browsers can open them too.

If you want to see videos, try NewPipe app as adviced above, it's a good free replacement for official YouTube app.
