### ISSUE TITLE
endchan bug

### ISSUE THREAD

**Issue by doonoo** [Mishiranu/Dashchan#142]
Sometimes I make a mistake trying to post a thread, but when i fix it i get a captcha error. Happens on /pol/.

**Comment by Mishiranu** [comment]
I don't understand you. What do you mean under "fix mistake in post"?

**Comment by doonoo** [comment]
Like i forget to add a attachment so i can make the thread, then when i add the attachment, it says "expired captcha" or something like that.

**Comment by Mishiranu** [comment]
Oh, you overcomplicated everything. The problem is that some boards require a captcha for new threads now and nothing more.
I released a new update with captcha support yesterday.
