### ISSUE TITLE
endchan colors (again)

### ISSUE THREAD

**Issue by doonoo** [Mishiranu/Dashchan#147]
Yeah he added more colors

https://endchan.xyz/operate/res/6358.html#q6492
https://endchan.xyz/.static/posting.html

Can you make  [meme][/meme] each letter a different color and [autism] the same just big letters (doesn't have to have the rainbow effect) or is that not possible?

**Comment by Mishiranu** [comment]
New colors added.

Yes, technically it's possible to make a rainbow but I won't do it.
