### ISSUE TITLE
Lainchan.org module doesn't work

### ISSUE THREAD

**Issue by decripter37** [Mishiranu/Dashchan#148]
As title say. They remade the site while ago, maybe something changed and broken the module.

**Comment by Mishiranu** [comment]
Just checked it. It seems that everything works.
What exactly is broken?

**Comment by nilesr** [comment]
I tried it this morning and got connection reset on everything, with https both enabled and disabled

**Comment by decripter37** [comment]
bump, it says: "Connection was reset"

**Comment by Mishiranu** [comment]
I can't reproduce it. "Connection reset" is network problem, there may be reasons why you can't access the server. Extension itself works similarly to other extensions and I don't see any reasons how its implementation may cause this issue.

**Comment by decripter37** [comment]
I'm on Android kitkat, huawei y625, maybe it's too old? I can't connect and it baffles me too
