### ISSUE TITLE
Модули не устанавливаются в среде Samsung My Knox

### ISSUE THREAD

**Issue by LeCroissant** [Mishiranu/Dashchan#149]
При попытке установить любой модуль в среде My Knox, моментально выходит ошибка "Приложение несовместимо с вашим устройством".

Прошу извинить за "индивидуальную" просьбу, но можете ли вы, Mishiranu, собрать один apk из Dashchan, модуля Двача и webm-кодеков?

**Comment by LeCroissant** [comment]
Я разобрался. My Knox больше не будет обновляться, ему на смену пришёл Secure Folder, где никаких проблем нет. 
Issue закрываю.

**Comment by Mishiranu** [comment]
Модули, вообще говоря, являются обычными приложениями и вовсе не понятно, по какой причине система отказывается их устанавливать. В любом случае я без лога установщика не смог бы это исправить.
Впрочем, возможно такое, в подобной среде работа модулей в принципе не возможна. Правда, проявлялось бы это не в невозможной их установке, а уже во время работы приложение, когда оно эти модули пытается загрузить.
