### ISSUE TITLE
More directory settings for saving images.

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#15]
I use this application for some considerable time. First of all, I would say that version 2.3 is the best version of that application until today, and that Dashchan is the best type of application if compared to standard functions and visual coherence.

My ideas are simple. The application works like this to go on batch image download window:

Gallery> button to select batch download> window for confirmation (if enabled in the settings) and downloads the images. I like that the images are downloaded batch stay marked in the gallery after performing this process. I do not think it's something a priority, but it's something you'd like to see in this application.

The second request are more options to choose from in the settings directory.

Currently the application saves the images as follows ..

a-123456789 (and here if the user wish the name to topic)
My idea is to save the files as follows
4chan / a / 12345687 - Code Geass General (for example) (placing an option in the settings for the user, to include the topic name in the folder)

A fix..
When an image is saved with detailed directory information, is currently saved as:
fourchan-a-12345678
it is possible to switch to 4chan (or any board that the user want to use) -12345678?

It is difficult to add these functions?

**Comment by Mishiranu** [comment]
Honestly, I don't understand your first request. You want a "download all images" button instead of selection all images like it works now? I think it's unnecessary to duplicate functions.

The second request is good. I think I can add a formattable default subdirectory option instead of hardcoded %channame%-%boardnam%-%threadnumber%.

"fourchan" is extension name *(chan name, as I called it)*. Extension names can contain only latin characters without numbers or any other symbols. I don't think that it's expedient to make it configurable. I think that "fourchan" is intelligible enough.

**Comment by GiRaFa-SM** [comment]
I will try to be clearer, when/after the batch download process is completed/started, the images remain marked, only for indication of which images were downloaded.

It can keep this effect if the user returns in a certain gallery?

Folders can have the website(in this case 4chan instead fourchan) Text?

Thank you for quickly reply. Glad to see a nice application with a nice support.

**Comment by GiRaFa-SM** [comment]
A question for you dev. 
Why this awesome app isn't published on Google Play?    

Have you ever problems publishing apps there?

**Comment by Mishiranu** [comment]
You mean keeping selection when you click "download files" button? It's impossible, because when background window loses focus (due to download dialog), It also resets selection mode. And why do it at all?

> Folders can have the website(in this case 4chan instead fourchan) Text?

Yes, but name takes from extension name.

> Have you ever problems publishing apps there? 

I've published it but it was deleted in 15 hours with this email:

> This is a notification that your application, Dashchan, with package ID com.mishiranu.chan, has been removed from the Google Play Store.
REASON FOR REMOVAL: Violation of the sexually explicit material provision of the Content Policy. Please refer to the Sex and Nudity policy help article for more information.

I decided to not publish it more.

**Comment by GiRaFa-SM** [comment]
NFSW boards was visible normally or the user need to add manually? Mimi4ChanReader (beta) was removed by the same reason. Google Play have stupid rules about apps that shows NSFW content. 

So imagens will be saved:
Fourchan/a/123456789? And if the user wants, add the topic name? 

Maybe if you publish a new version with a function to add boards manually(showing only SFW Boards) and a visual alert if the user want add NFSW boards..

**Comment by Mishiranu** [comment]
There weren't any boards in client, lol. When user launched the app, he saw a text field with "go" button. User could add boards to favorites. And this version was banned.

![device-2015-10-08-020931](https://cloud.githubusercontent.com/assets/8524113/10352665/47fe6e3e-6d59-11e5-97a4-d670877792c4.png)

Yes, something like that. But I don't sure about thread title, maybe I'll add it later.

**Comment by GiRaFa-SM** [comment]
I don't really know what to say, unless think that the terms of the Google Play use are stupid or don't make sense.

I would not say for you to try again if your application is banned again, Google may "end your developer career." If you want publish other type of app on Google play, and if you come to be interested, there are several instances of the same type on the Internet.

Yeah, no problem with that. If the user still can edit the thread name manually. 

Thank you again for this app.

**Comment by Mishiranu** [comment]
I decided to do so:

![device-2015-11-06-054155](https://cloud.githubusercontent.com/assets/8524113/10987076/d1190118-8440-11e5-8193-d6697bf35b34.png)

You'll be able to configure your own pattern. In your case

> 4chan / a / 12345687 - Code Geass General

you can use something like `\d/\b/\t< - \e>`. Text inside `<>` will be removed when title is empty.

**Comment by GiRaFa-SM** [comment]
Man you're the best. Now I don't have literally any reason to use any other app. 

I found a litre complicated when I saw the new option, but thank you for show me how to configure it. And you made a more dynamic setting than I thought. Thank you very much man.

**Comment by Mishiranu** [comment]
>I found a litre complicated when I saw the new option

I'll make a guide later.
