### ISSUE TITLE
Сосач запретил постинг с телефонов

### ISSUE THREAD

**Issue by fapfapfapchan** [Mishiranu/Dashchan#150]
С модуля сосача для даши нельзя постить

**Comment by Folky63** [comment]
Фсбач совсем скатился, скоро без включенной вебки и бутылки в заду постить запретят

**Comment by laz2727** [comment]
Можно, просто обход не работает.

**Comment by randseed** [comment]
Так это обезьяна там что-то намеренно запретила, или просто какая-нибудь мелочь в макабе поменялась?
Это поправимо?

**Comment by Mishiranu** [comment]
Обхода капчи больше не будет. Убрал возможность его выбора, так что теперь ошибка появляться не будет.
