### ISSUE TITLE
General modules

### ISSUE THREAD

**Issue by smalltock** [Mishiranu/Dashchan#151]
I think it would be good to have general modules that aren't tailer-fitted to a particular website, but are instead made for a particular chan software, like lynx-chan.  This way, minimum trouble would be needed to add basic functionality for XXXX-chan.  Instead, a user would grab the plugin that matches the software that his obscure chan uses.  Open the app, punch in the url, and you're golden.  Devs wouldn't have to be bothered about it.  Sound good?

**Comment by devarped** [comment]
It has already been [discussed](https://github.com/Mishiranu/Dashchan/issues/89). 
Mishiranu had an idea to do so, but in his opinion there is no chans with fully identical engines (there is different engine versions, different locales, different timezones, etc.), and so it's easier for him to make individual modules than creating a general ones which would be too complicated.

**Comment by smalltock** [comment]
Okay, thank you.  Sorry, I didn't realize.
