### ISSUE TITLE
Сортировка модулей по категориям

### ISSUE THREAD

**Issue by devarped** [Mishiranu/Dashchan#154]
Собственно, сабж. Уверен, что у дашчана есть много пользователей, у кого установленно с десяток или больше модулей и кто бы хотел их упорядочить. Им бы эта функция пригодилась.

**Comment by Mishiranu** [comment]
Пользователь может создать свои категории и затем раскидать модули по ним? По-моему это перебор совсем. В крайнем случае, их можно упорядочить как удобно.

**Comment by devarped** [comment]
Ну ладно.
