### ISSUE TITLE
Navigate to post on quotes.

### ISSUE THREAD

**Issue by Gfurst** [Mishiranu/Dashchan#157]
The idea here is to have the "quote popup" close and scroll back to the post in question, when you click only. Without it you have to close the whole chain of quotes and find it manually. 

Somewhat similar behavior with the clover app.

**Comment by Mishiranu** [comment]
It's already done in https://github.com/Mishiranu/Dashchan/commit/33ba4213202a1c5432f7fc32d05055e994db9633, will be available in next release.

**Comment by Gfurst** [comment]
Wow, that was quick, thanks mate!
