### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by thebettersort** [Mishiranu/Dashchan#16]
I've been using Daschan for a while alongside Clover and Exodus. I have a few suggestions for frautes, some of which have been requested here before but dismissed due to possible lack of people wanting the change. I tried to stick to issues that are easy to implement (unlike the open WebM issue)

I, and some people I've spoken to, would love to see:
- When text scaling is set at less than 100%, the top of the first line of text is hidden behind the thread's padding

- Sometimes when browsing a thread and clicking replies (and then following the replies for the reply we were first previewing) it can become a long process to close all the preview windows and go back to the thread. Maybe a "Close" button like Clover would be a good idea? It's somewhat inconvenient to have to press Back an unknown number of times.

- An option to view boards in tile view instead of card view (A global setting somewhere, ideally. Again similar to Clover's default), but maybe only view tiles in Catalog mode, similar to the way chans work by default on their websites.)

- A global toggle to view Catalog mode by default.

- Maybe an option to turn the notifications from saving a file into regular tray notification cards instead of heads-up notifications? (Unless this already exists somewhere)

Thanks very much for considering all this, feel free to ask for  clarification. Thank You :)

**Comment by GiRaFa-SM** [comment]
Staggered Grid View on Catalog isn't bad in my opinion. I don't use it, but is nice.

**Comment by Mishiranu** [comment]
> When text scaling is set at less than 100%, the top of the first line of text is hidden behind the thread's padding
You want thread title to be outside a card? I think it will look like a shit. Or I don't understand you...
> Sometimes when browsing a thread and clicking replies...
Make a long press on back button and all dialogs will be closed.
> An option to view boards in tile view instead of card view
Menu -> Appearance -> Threads grid
> A global toggle to view Catalog mode by default.
Not all imageboards have a convinient and detailed catalog (e.g. krautchan) and it can be a problem. I don't know a good way to make this option.
> Maybe an option to turn the notifications from saving a file into regular tray notification cards instead of heads-up notifications?
Preferences -> Attachments -> Notify when download is completed

**Comment by thebettersort** [comment]
Thank you both for your quick responses.
As for the first "issue"
 Here's a picture of what I'm talking about. Notice that the first line is hidden.
![screenshot_2015-10-18-08-44-49](https://cloud.githubusercontent.com/assets/5108072/10564104/c69a8408-7574-11e5-966f-49b695b71153.png)

Maybe the text should be moved down a few pixels?
Thanks

**Comment by Mishiranu** [comment]
You are right, it's a bug. I'll fix it.

**Comment by thebettersort** [comment]
Also I just tried holding back to close dialogs and it didn't work. At least on my device.

**Comment by GiRaFa-SM** [comment]
It's working well on my device.. 
Galaxy S4 GT-i9505 @ JDCT ROM 5.1.1

**Comment by thebettersort** [comment]
Not on mine. HTC One M9

**Comment by Mishiranu** [comment]
It's strange. Can you contact me by email? I need to test something on your device.

**Comment by thebettersort** [comment]
Contacting now.

**Comment by Xyllon** [comment]
>Not all imageboards have a convinient and detailed catalog (e.g. krautchan) and it can be a problem. I don't know a good way to make this option.

Would it be possible to make it an imageboard-specific setting?

**Comment by dockingthepod** [comment]
Is there any way to sort board content by most replies rather than bump order?

**Comment by Mishiranu** [comment]
You can do it in catalog mode: click on the title block (with "Catalog: ..." text) and you will see the sorting options.

**Comment by dockingthepod** [comment]
Awesome man, thank you. This was an easy and smooth transition from Chanu.

**Comment by Mishiranu** [comment]
> Would it be possible to make it an imageboard-specific setting for those that would work?
So I did.
