### ISSUE TITLE
[arhivach] Не открывает тред по номеру

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#161]
Ввожу номер треда - не открывается.

**Comment by Mishiranu** [comment]
Потому что в архиваче своя нумерация тредов. При просмотре треда отображается номер исходного треда, но в адресной строке тред идентифицируется по его номеру на архиваче. Этот номер нельзя получить, зная адрес исходного треда, поэтому оно так работает.

**Comment by ololoe** [comment]
ЯННП. Почему `arhivach.org/thread/123456/` открывается, а `123456` нет?

**Comment by Mishiranu** [comment]
Потому что `123456` означает переход на эту страницу, а вовсе не в тред с этим номером. Используй `$123456`. Информация по этому полю есть в [FAQ](https://github.com/Mishiranu/Dashchan/wiki/Guide-RU#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8F-%D0%9A%D0%BE%D0%B4-%D0%BD%D0%BE%D0%BC%D0%B5%D1%80-url).

**Comment by ololoe** [comment]
Почему нельзя просто использовать `номер_треда`?

**Comment by Mishiranu** [comment]
Потому что уже используется номер страницы.

**Comment by ololoe** [comment]
Имхо было бы интуитивнее сделать наоборот

**Comment by Mishiranu** [comment]
Об этом надо было думать 3 года назад.

Ну и вообще мне текущий вариант кажется логичным.

**Comment by ololoe** [comment]
Шо з воза упало, то пропало? :) Никто не мешает поменять.

**Comment by Mishiranu** [comment]
Мешает то, что за 3 года все привыкли, что оно работает именно так, как 
работает сейчас.

И я не вижу ни единой причины, почему оно должно работать так, как ты 
говоришь.

**Comment by ololoe** [comment]
Ну фиг с тобой, не меняй.
