### ISSUE TITLE
4chan /pol/ flags

### ISSUE THREAD

**Issue by deathpaladin** [Mishiranu/Dashchan#164]
Can you add the custom flags from /pol/ and make it possible for users to choose a custom flag when posting?

**Comment by Mishiranu** [comment]
I heard about this feature. The problem is that 4chan doesn't provide API to obtain all flags to display them to user. So I need to hardcode them or fetch from web GUI directly.

I'll think about it later.

**Comment by tjoAU** [comment]
Bumping because this is the one thing Kuroba does better
Would be perfect if you could pick your own flag and display meme flags

**Comment by Mishiranu** [comment]
> The problem is that 4chan doesn't provide API

Actually it does, at least for now. You'll need to reload the list of boards to reload flags from the server.

**Comment by Mishiranu** [comment]
Should work in 4chan extension v1.19.
