### ISSUE TITLE
"No access to memory" error on Nexus 7 (2013, Wi-Fi), Android 6.0

### ISSUE THREAD

**Issue by maxim-b-dev** [Mishiranu/Dashchan#17]
After updating to 6.0 I can no longer open attached media, always getting the "No access to memory error". Thumbnails display fine.

**Comment by maxim-b-dev** [comment]
Suspected it could be a firmware issue, but even after flashing stock 6.0 I get the same error.

**Comment by Mishiranu** [comment]
Maybe storage permission is disabled for Dashchan? Open Settings - Apps - Advanced - App permissions - Storage. Is it enabled for Dashchan?

**Comment by maxim-b-dev** [comment]
Great, this seems to have fixed it. Dashchan never asked for storage permission on install, so you might want to look into that.

**Comment by Mishiranu** [comment]
Yes, you are right. Developers must request permissions by themselves. I'll fix it in next version.
