### ISSUE TITLE
"Load nearest image" not working properly

### ISSUE THREAD

**Issue by gonztok** [Mishiranu/Dashchan#173]
I have it set to "Always" but when I swipe to the next image it shows the thumbnail while the full resolution version loads. To confirm this I set the option "Load thumbnails" to "Never" then I get a blank space while the image loads.

**Comment by Mishiranu** [comment]
Does it never work or sometimes only? "Nearest" mean right or left depending on direction you are scrolled before.

**Comment by gonztok** [comment]
Yes, it happens all the time. I just uploaded a video : https://www.youtube.com/watch?v=7pj9cs3a3UA

BTW, I´m using a Moto X Style running Nougat 7.0 if that matters.

 

De: Fukurou Mishiranu [mailto:notifications@github.com] 
Enviado el: martes, 10 de octubre de 2017 9:12 p. m.
Para: Mishiranu/Dashchan <Dashchan@noreply.github.com>
CC: gonztok <gonztok@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Mishiranu/Dashchan] "Load nearest image" not working properly (#173)

Does it never work or sometimes only? "Nearest" mean right or left depending on direction you are scrolled before.

**Comment by Mishiranu** [comment]
According to your video it seems to work. You don't see the loading 
progress so it loaded from cache since it was loaded while you looked at 
previous image.
You are seeing the preview because image is not actually loaded to 
memory but downloaded from server and stashed to you sdcard. It's a 
correct behavior.

**Comment by gonztok** [comment]
Ah! I just misunderstood how it worked. I assumed it would load the next image into memory so when I swipe it would give the impression I was swiping through a local gallery. Thanks or your reply!

 

De: Fukurou Mishiranu [mailto:notifications@github.com] 
Enviado el: martes, 10 de octubre de 2017 11:33 p. m.
Para: Mishiranu/Dashchan <Dashchan@noreply.github.com>
CC: gonztok <gonztok@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Mishiranu/Dashchan] "Load nearest image" not working properly (#173)

 

According to your video it seems to work. You don't see the loading 
progress so it loaded from cache since it was loaded while you looked at 
previous image.
You are seeing the preview because image is not actually loaded to 
memory but downloaded from server and stashed to you sdcard. It's a 
correct behavior.
