### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by loxpro123** [Mishiranu/Dashchan#176]
На днях обновил телефон до android 7.0 NRD90M, Miui 9.1.1.0. После этого пропали надписи на экране (captions), которые при открытии тредов выскакивали с кол-вом новых сообщений и кнопкой "к новым постам" - это самая офигенная фича и она отвалилась. Можно это починить? Версия сброки 2.10.3, если что.

**Comment by Mishiranu** [comment]
Информация о количестве сообщений вычисляется исходя из текущих данных в кэше. Данные в кэше живут довольно долго, особенно это касается избранных тредов (для них кэш вообще никогда не очищается).

Если надписи нет, значит данные были впервые загружены в кэш. Скорее всего, это из-за того, что твоя прошивка занимается самостоятельной очисткой кэша когда ей это вздумается. Я что-то слышал про «оптимизацию MIUI», вероятно, с этим оно и связано.

Работа с кэшом тредов — фундаментальный принцип работы приложения. Если на какой-то прошивке вдруг решили заниматься чисткой кэша без ведома пользователя и разработчика, то это проблема прошивки. Насколько я знаю, эту оптимизацию можно вовсе отключить.
