### ISSUE TITLE
Existe um bug no apk do 55chan

### ISSUE THREAD

**Issue by 3hrmantraut** [Mishiranu/Dashchan#179]
Quando vamos postar qualquer coisa devemos passar por um re-captcha do site e não da google então o mesmo não e apresentado e não tem como enviar o fio.

**Comment by nadadepao** [comment]
Você tem que acessar o captcha pelo navegador para então postar pelo aplicativo.

**Comment by Gfurst** [comment]
Confirmo esse bug. E porque estamos falando em português, vai assumi que o maintainer do apk também fala nossa língua?
