### ISSUE TITLE
is candydollchan (listed extention) cp?

### ISSUE THREAD

**Issue by Waterflash** [Mishiranu/Dashchan#180]
if so, remove it immeadiatly

**Comment by Mishiranu** [comment]
I don't know. I provide modules, not services. Deleting them is like blacklisting access to some sites in browser.

**Comment by Waterflash** [comment]
ok sry for the harsh response. i researched a bit about the term candy doll and it seems to be CP, but kept right at the border before it can become illegal. I don't know if that applies to every country though
tbh i don't give two shits about legal stuff (as long as i can still use your awesome app). i'm just worried that it could be harmful to children and sharing it would just expand the community, wich means even more making&sharing.

Sorry I'm just a bit sensitive bout it
