### ISSUE TITLE
Flags on 8ch /christian/ and other boards

### ISSUE THREAD

**Issue by theRitz7** [Mishiranu/Dashchan#182]
Hey, I noticed that there's flags on 4chan, but not on 8ch. /christian/ and /pol/ are the only ones I have noticed this issue with. It's not vitally imporant to posting on those boards imo, I just think it would be nice to see.

**Comment by Mishiranu** [comment]
Unfortunately, 8ch doesn't provide info about flags in their API. I use API when it's available so I can't obtain flags for posts. You can try to contact board admins and ask about it.
