### ISSUE TITLE
Recaprcha v2 dvach

### ISSUE THREAD

**Issue by xeyalxx** [Mishiranu/Dashchan#185]
Рекапча с "машинами" и "дорожными знаками", а может быть и ещё , что-то, не отображает текст " нажмите на картинки с машинами/дорожными знаками", а просто картинки без надписи сверху, в то время как с "мостами", " автобусами" и "домами" всё в порядке, и над картинками висит надпись "select all images with an bus/appartament building/bridges".

**Comment by ololoe** [comment]
>  "select all images with an bus/appartament building/bridges".

У меня только эти 3 категории отображались.
