### ISSUE TITLE
Вылетает при попытке поделиться файлом

### ISSUE THREAD

**Issue by plshlpme** [Mishiranu/Dashchan#186]
Система: Android 8.0
При попытке поделиться любым файлом, будь то изображение или вебм, вылетает дашчан. Прикрепляю лог ниже.
[error-1515008297425.txt](https://github.com/Mishiranu/Dashchan/files/1601487/error-1515008297425.txt)

**Comment by F1nZeR** [comment]
Когда релиз с этим фиксом можно ждать?
