### ISSUE TITLE
Captcha 2ch

### ISSUE THREAD

**Issue by Flagitio** [Mishiranu/Dashchan#187]
Появилась ошибка 400 bad request при попытке запросить капчу, соответственно постить стало невозможно, капча не отображается, ошибка возникла спонтанно без видимых причин, другие типы капч не работают.

**Comment by Mishiranu** [comment]
Как минимум есть 2 типа капч — recaptcha 2 и malru. Они обе 400 bad request выдают или что?

**Comment by Drunkergnom** [comment]
Recaptcha 2 не работает совсем, mail.ru стабильно выдает ошибочное введение.

**Comment by Mishiranu** [comment]
Мейлру работает. Может, ошибочное введение выдаёт потому что ты вводишь 
неправильно?

**Comment by sookabazooka** [comment]
Та же проблема, не работают все виды капчи кроме мейловской, но мейловская постоянно загружает новую

**Comment by Mishiranu** [comment]
Мне подсказали, что капча мейлру работает только если указан домен 2ch.hk. На 2ch.pm, например, уже не работает.
Я думаю, что это должны были бы исправить на стороне сервера, впрочем, капча мейлру скоро перестанет работать, так что смысла переживать уже нет никакого.

**Comment by yaxn** [comment]
![screenshot_20180203-131041](https://user-images.githubusercontent.com/32079011/35766168-c6721e1e-08e3-11e8-93b9-b9e8bb175361.png)
Вот такая вот проблема вечно возникает с капчей о гугла: нет описания  что нужно выбрать. Описание появляется через два-три неправильных ввода, очень редко появляется сразу

**Comment by alexey-formalmethods** [comment]
@yaxn , same for me. 
Отмечу, что можно кликнуть на рандом пикчу, отправить и получить новую капчу, в половине случаев появляется вопрос, что именно нужно разгадать.
