### ISSUE TITLE
Решалка капчи (платная)

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#188]
Когда добавишь? Есть уже готовые модули.

**Comment by ololoe** [comment]
Ответь что-нибудь.

**Comment by Mishiranu** [comment]
Никогда не добавлю.

**Comment by ololoe** [comment]
И почему же?

**Comment by Mishiranu** [comment]
Идея не нравится.

**Comment by ololoe** [comment]
И что не нравится? Неужели русня такая нищая, что не может себе позволить 1000 капч меньше чем за бакс?
Я бы вбросил в обсуждение, но только ебаный мудак мог придумать все обсуждения в едином треде, где невозможно отслеживать ответы.

**Comment by Rrarity** [comment]
> 1000 капч меньше чем за бакс

**Comment by ololoe** [comment]
https://rucaptcha.com/

**Comment by ololoe** [comment]
И в конце концов таки добавил.
