### ISSUE TITLE
Thumbnails don't load properly

### ISSUE THREAD

**Issue by tayser1** [Mishiranu/Dashchan#189]
While browsing threads in 4chan the thumbnails don't load while scrolling. It's really annoying. Thumbnails only start loading after releasing my finger from screen AND it must stop scrolling.

**Comment by Mishiranu** [comment]
That's a correct behavior. It loads only when you aren't scrolling the screen.

**Comment by tayser1** [comment]
Please add the function to load thumbnails while scrolling. This feature will make the browsing experience much smoother and enjoyable.
