### ISSUE TITLE
All "*.apk" files on the main page result in "Can't open file" even with unknown sources enabled.

### ISSUE THREAD

**Issue by PharmaceuticalCobweb** [Mishiranu/Dashchan#199]
I'm on the Moto G 4G XT1039 (Peregrine) with LineageOS 14.1 (Andorid 7.1.2).

Attempting to open any of the "*.apk" files on the main page results in the ambiguous error "Can't open file".

Unknown sources are enabled. Device is rooted. I've tried running the client application apk first. Then I tried installing various extension packages and even the webm libraries. All result in the same error.

I've been able to install other "*.apk" files but none from the Dashchan project seem to work for me.

Bug? Or just my phone being prehistoric? Or am I just being dumb?

**Comment by advocate441** [comment]
Same issue on Blackberry Passport: unable to install package.

**Comment by Mishiranu** [comment]
Now you should be able to install extensions from the client directly.
