### ISSUE TITLE
Make webms play inside app

### ISSUE THREAD

**Issue by iiiGerardoiii** [Mishiranu/Dashchan#2]
It would be nice to play webms inside Dashchan without having to use an external media player app.

**Comment by Mishiranu** [comment]
Built-in system features don't allow to make a good WebM player. It's impossible to implement video streaming. Even without streaming some videos will play without sound or image. It is also very dependent on the device.

The only way to make a good player is using software decoding. I must use external libraries for this. It's really not easy and it will take a lot of time. The app will weight 5 times more in result.

There are a lot of players that can play WebM by themselves. The goal does not justify the means.

**Comment by iloveclover** [comment]
Yeah external webm players are way better than inline webm viewing.

**Comment by soupman2001** [comment]
Which external app would y'all recommend for use with the kind of webm files posted on imageboards? One that loops them by default would be nice.

**Comment by Mishiranu** [comment]
MX Player, for example. You can enable loop in Menu - Play - Loop one.

**Comment by GiRaFa-SM** [comment]
Even using MXPlayer isn't the same thing that see on PC and others 4chan(loops seems weird) tbh. 

But I respect your opinion dev, this app is top tier and the best characteristic is be lightweight, well optimized, and can be personalized by the user, with 800kb.

**Comment by libeclipse** [comment]
Clover managed to implement this.

**Comment by Mishiranu** [comment]
Clover uses system MediaPlayer, not software decoding.

**Comment by Mishiranu** [comment]
Webm player was added in last version. It's experimental feature now.
You need to download [this](https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanWebm.apk) extension with codecs to make player work.

**Comment by IWillRedPillYou** [comment]
Link is 404 to webm extension please update thx

**Comment by Mishiranu** [comment]
README contains a correct link but wiki doesn't. Fixed.
