### ISSUE TITLE
captcha expired

### ISSUE THREAD

**Issue by kunikomithra** [Mishiranu/Dashchan#20]
help, it's impossible to post because it keeps saying captcha expired

**Comment by Mishiranu** [comment]
Where is it? When exactly this message appears?

**Comment by kunikomithra** [comment]
whenever i try to post and complete the captcha, it says "expired"

**Comment by Mishiranu** [comment]
On which imageboard?

**Comment by Mishiranu** [comment]
I realized what happened, I'll fix it later.
You can switch to old recaptcha in preferences, it works correctly.

**Comment by GiRaFa-SM** [comment]
Thank you for come here and report the issue from developer. 

By the way, I'm using the old captcha and I don't have this error.

**Comment by Mishiranu** [comment]
Fixed in last update.
