### ISSUE TITLE
How to delete a post?

### ISSUE THREAD

**Issue by Gfurst** [Mishiranu/Dashchan#202]
Forgive me if this comes as some obvious answer, but I wasn't to find how can you delete something you've posted, either image or the post itself. Even though there is a kept password exactly for that. 

Where is it supposed to be placed? And if that feature indeed exists, so its dependent on the specific forum plugin?

**Comment by Xyllon** [comment]
Long press the post and there should be an option to delete.

**Comment by Gfurst** [comment]
> Long press the post and there should be an option to delete.

Okay, so indeed I tested it and it appears on some but not all forums, so its plugin dependent.

**Comment by devarped** [comment]
>its plugin dependent
More like board-dependent, on some sites deletion could be disabled or not implemented.
