### ISSUE TITLE
Captchas not working in latest release.

### ISSUE THREAD

**Issue by mateodif** [Mishiranu/Dashchan#208]
In the latest release (2.10.4), the captchas are not working, at least for 4chan.
Steps to reproduce:
1) Install latest version with 4chan and webm support.
2) Try to post, load the captcha.
3) Complete the captcha successfully and post.
4) Try to post again.
When you try to post again, the captcha will disappear every time you select a "square" of it, only to reappear again with the same problem. This happens a couple times more until it gives up and keeps trying to load the post to no avail. The weird thing is, the first time you try to post the captcha works fine, however every time after that it won't work at all.
The captcha is working fine on 2.10.3. Cheers.

**Comment by Xyllon** [comment]
Hopefully this gets fixed soon, I'm forced to use Clover for the time being and it's so much worse IMO.
