### ISSUE TITLE
Флажки в pol

### ISSUE THREAD

**Issue by Jacklinks** [Mishiranu/Dashchan#209]
Нельзя ли запилить полную поддержку флажков в пол форчана? Meme-флаги не отображаются, выбрать их при постинге тоже нельзя. Там ещё цвета есть, но без этого можно обойтись - они рандомные, вроде, и ничего не значат, а вот флажки - пожалуйста-пожалуйста!

Ах да - айди тоже не отображаются!

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/issues/164
