### ISSUE TITLE
Multi quote feature? 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#21]
This feature already exists?

**Comment by Mishiranu** [comment]
No. You can reply to multiple posts at once but not quote them.

**Comment by GiRaFa-SM** [comment]
Teach me please? First I thought that I needed press select on context menu and select the posts I want reply, but that is the only way to respond multiple posts? Thank you.

**Comment by Mishiranu** [comment]
It's the only way.

**Comment by GiRaFa-SM** [comment]
Nothing too much different than the PC version to be honest. You think is possible to improve the reply system with my idea above?

**Comment by Mishiranu** [comment]
You want a button to quote all selected posts?

**Comment by GiRaFa-SM** [comment]
Yes, but I wanted know your opinion about it. You're the app developer.

**Comment by Mishiranu** [comment]
I think it's not necessasy. You can't select what to quote so all posts will be quoted. It makes no sense because you'll reply for entire post in any case and you can do it with multi reply button.
Also there is no place for one more button in action bar.

**Comment by GiRaFa-SM** [comment]
Closing this issue then.

**Comment by GiRaFa-SM** [comment]
It's just me or this feature was implemented silent? Because when I press select I have 3 buttons and one of them works to make multi-replies.

**Comment by Mishiranu** [comment]
> You can reply to multiple posts at once but not quote them.

It was implemented a long ago.
