### ISSUE TITLE
Капча на форче

### ISSUE THREAD

**Issue by cocuette** [Mishiranu/Dashchan#213]
Капча просто убийственно долгая, тупит невозможно. По двадцать раз приходится выбирать светофоры, и все равно ничего не происходит.

**Comment by vanonomervano** [comment]
@cocuette 
>use JavaScript for recaptcha
>recaptcha 2
Пробовал ставить?

**Comment by cocuette** [comment]
Recaptcha 2 стоит по дефолту и работает коряво, а recaptcha даже не загружается и не позволяет прикреплять картинки.
