### ISSUE TITLE
Invalid server response (error) when browsing 8ch.net 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#22]
Happens when I'm swiping to reach at page 2, after this a toast notification says "invalid server response." 

Reloading board doesn't works.

**Comment by Mishiranu** [comment]
Because 8chan regenerates only first 2 pages. The rest pages are unavailable.

**Comment by GiRaFa-SM** [comment]
So isn't possible to fix it? (I visited this site once or twice on my PC, and I don't know if in desktop version happens that) In the past versions it was possible to navigate on more pages...

**Comment by Mishiranu** [comment]
No. Even in browser you can view first 2 pages.
Some weeks ago it was possible. I think it's a way to reduce a load on server.

**Comment by GiRaFa-SM** [comment]
Thank you for your support Mishiranu. I'll close this issue.
