### ISSUE TITLE
CAPTCHA + 4chan Pass issues (and temp fixes)

### ISSUE THREAD

**Issue by ghost** [Mishiranu/Dashchan#220]
Mostly creating this issue for people wondering how to get stuff working.

If you're having issues with CAPTCHA, untick "Use JavaScript for reCAPTCHA" in General.

If you're having issues logging into your 4chan Pass:

1. Uninstall Dashchan and all extensions

2. Download all the Dashchan APKs you need and use [this](https://files.catbox.moe/rs6jn9.apk) instead of the 4chan extension provided (you can also build the APK for yourself from [here](https://github.com/desertkun/Dashchan-Extensions/tree/fourchan-passcode-fix)).

3. Download and install [ZipSigner](https://www.apkmirror.com/apk/ken-ellinwood/zipsigner/zipsigner-3-4-release/zipsigner-3-4-android-apk-download/).

4. Sign all Dashchan APKs with test-keys (or your own keys, it doesn't really matter - they just all have to be signed with the same set).

5. Install them as normal.

When it finally gets fixed officially you'll need to uninstall everything again so you can use the APKs signed by @Mishiranu.

**Comment by ftrotyo** [comment]
It keeps saying "this recapcha is not supported" for both expetensions
