### ISSUE TITLE
[АНОНИМНОСТЬ] Какие данные передает/хранит дашчан, кроме кукисов?

### ISSUE THREAD

**Issue by sucud** [Mishiranu/Dashchan#221]
Есть ли Local Storage, Indexed DB, Session Storage, Cache Storage, как в других браузерах? Есть ли уникальный ID у браузера, который видит борда? Есть ли иные способы фингерпринтинга, о которых я не упомянул?

**Comment by Mishiranu** [comment]
Dashchan — не браузер, и браузерных технологий, вроде того же Indexed DB, не использует. Есть собственное хранилище, которое используется в основном для хранения каких-то переменных и настроек, и в основном используется только внутри приложения, т.е. данные из него уходят только в редких случаях (если вообще уходят, потому что я точно не помню, нужно смотреть код конкретных модулей).

Есть хранилище кук, которые можно посмотреть, удалить, или даже заблокировать в настройках, причём хранятся только необходимые куки, а не все, что приходят с сервера. И отправляются куки тоже не все и не всегда.

Можно посмотреть код интересующего модуля, в классах *ChanPerformer описывается работа с куками и хранилищем, и кода не так много. Это методы get/set для работы с настройками и getCookie/storeCookie для работы с куками.

Пример работы с куками в модуле dvach. Есть кука сессии, она всегда хранится и передаётся, она же разблокирует доступ к 18+ доскам. Её можно заблокировать. Есть кука, в которой хранится авторизация по пасскоду, в случае использования этого самого пасскода, но передаётся только при запросе капчи или отправке сообщения. Хранятся куки создателя тредов, чтобы можно было ставить метку OP в своих сообщениях, но передаются они только если поставить соответствующую галочку при отправке.

Dashchan идентифицирует себя как Google Chrome под андроид через User-Agent, его можно поменять через advanced preferences (см. вики).

Если говорить о фингерпринтинге, довольно несложно по заголовкам и способом работы с сервисом понять, что человек пользуется именно дашчаном.

**Comment by sucud** [comment]
Как посмотреть код модуля?
То есть чисто теоретически модуль способен хранить какой-нибудь ID в "собственном хранилище" дашчана, которое не удаляется через чистку кеша? Которое можно удалить только через Apps-Dashchan-Clear data?

**Comment by sucud** [comment]
Тем самым заодно стерев все настройка дашчана.

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan-Extensions

Код модулей находится в разных ветах в зависимости от модуля. Например, для 2ch.hk ветка называется dvach.

**Comment by s1q** [comment]
Шизоиды, что вы вечно из себя строите? Бери исходники и читай.
