### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by dadrilla** [Mishiranu/Dashchan#229]
После ввода капчи ничего не происходит, появляется сообщение неправильная капча, с чем в корне не согласен, попадалась капча с четко нарисованными цифрами, все ввел, перепроверил, исход тот же.
телеф oukitel k10000pro

**Comment by dadrilla** [comment]
https://imgur.com/a/rj1mLBS

**Comment by CesPaul** [comment]
Вместо "2chaptcha" используй "reCAPTCHA 2" в Настройки -> Форумы -> [Используемый форум] -> Тип капчи
При постинге будет выводиться капча, которая выглядит так: http://www.imageup.ru/img255/3427978/photo_2019-07-16_17-58-01.jpg
Такая капча работает.

**Comment by dadrilla** [comment]
хуево братан все сделал выдает ошибку загрузки, пробовал с вайфая и мобильного, инет есть 100% иначе бы я тут не писал лол
https://imgur.com/a/49aoXls

**Comment by dadrilla** [comment]
а, неважно, ya eblan галочка на жава скрипт рекапче стояла, убрал. роботает. довольно урчу.
