### ISSUE TITLE
Счётчик новых постов в избранном показывает <?>

### ISSUE THREAD

**Issue by aosfan** [Mishiranu/Dashchan#234]
@Mishiranu 
Счётчик новых постов перестал работать, показывает вопросики рядом с количеством новых постов и не обновляется.
Если тапнуть на счётчик рядом с конкретным тредом, то он обновляется и показывает количество новых постов.
Зой, зделой, силушек моих больше нет. Могу задонатить, только почини.
![dash](https://user-images.githubusercontent.com/29099263/70435619-59132700-1a98-11ea-9de5-86697ce80063.png)

**Comment by dimqua** [comment]
В форке починили.
