### ISSUE TITLE
4chan keeps telling me that the captcha is not supported 

### ISSUE THREAD

**Issue by ftrotyo** [Mishiranu/Dashchan#235]
Reinstalled it a couple times and tried 2 different extensions
Unclicked "use Java script" still tells me the same thing 
![Screenshot_2019-12-20-09-36-26](https://user-images.githubusercontent.com/59096315/71278402-5d4b0a00-230c-11ea-988d-32fa56645807.png)

**Comment by JoeSaunders** [comment]
Same issue.

**Comment by Mishiranu** [comment]
Should work now.
