### ISSUE TITLE
Перезагрузка

### ISSUE THREAD

**Issue by ioDar65** [Mishiranu/Dashchan#239]
Телефон уходит в перезагрузу после открытия приложния 3.0.0
- LG V30

**Comment by Mishiranu** [comment]
Это уже что-то совсем дикое, на самом деле. Есть ли возможность как-то лог снять? Например, через adb подключить к компьютеру и сделать `adb logcat`, и затем запустить приложение и посмотреть, что оно там перед перезагрузкой пишет.

**Comment by ioDar65** [comment]
[2020-09-18-17-17-26[1].txt](https://github.com/Mishiranu/Dashchan/files/5246051/2020-09-18-17-17-26.1.txt)
не знаю🤔, сделал при помощи [https://play.google.com/store/apps/details?id=com.nolanlawson.logcat](catlog)

**Comment by drupavlovich** [comment]
У меня так же. Сегодня утром предложил обновление прям в клиенте. Обновил и решил запустить - черный экран на секунду-две, далее как будто включение после перезагрузки, при этом приложения открытые ранее висят в фоне, То есть вроде и не перезагрузка. Удалил, хотел откатиться на старую версию, но не нашёл апк. Позже обнаружил task manager'ом висящий даш в процессах, хотя я его удалял. Телефон SHARP S10 на 8 ведроиде. Пофиксь плиз или дай старую версию

**Comment by Mishiranu** [comment]
@ioDar65 без рута подобные приложения ничего не снимут. Полный лог можно только через adb получить, или с рутом.

**Comment by XakepSDK** [comment]
adb logcat https://gist.github.com/XakepSDK/76e89575eebf6c6de3b5ef36fba397fc

**Comment by Mishiranu** [comment]
That's funny, and this is acually a known issue https://proandroiddev.com/ca122fa4d9cb.

**Comment by Mishiranu** [comment]
Can someone test this? It's an apk file, github doesn't allow to upload them, so I renamed it to zip. Just rename it back.

[Dashchan-test.zip](https://github.com/Mishiranu/Dashchan/files/5264876/Dashchan-test.zip)

**Comment by XakepSDK** [comment]
Работает, бага нет

**Comment by Mishiranu** [comment]
Ага, отлично. Где-нибудь завтра постараюсь обновить тогда.

**Comment by ioDar65** [comment]
> That's funny, and this is actually a known issue https://proandroiddev.com/ca122fa4d9cb.

полностью статью не читал, получается, это из-за попытки вывести уведомление чи не?

**Comment by Mishiranu** [comment]
Не совсем, скорее, при попытке зарегистрировать канал уведомления (чтобы пользователь в системных настройках потом мог этот канал настроить). Видимо, система сериализует информацию о канале в каком-то JSON формате, а из-за ошибки в коде это приводит к тому, что крашится системный сервер и телефон перезагружается.

**Comment by Art1933** [comment]
> Can someone test this? It's an apk file, github doesn't allow to upload them, so I renamed it to zip. Just rename it back.
> 
> [Dashchan-test.zip](https://github.com/Mishiranu/Dashchan/files/5264876/Dashchan-test.zip)

Всё работает отлично,вылетов не наблюдается
