### ISSUE TITLE
Swipe to Dismiss Favorites/Open pages

### ISSUE THREAD

**Issue by Triodan** [Mishiranu/Dashchan#24]
It'd be nice if we can use swiping gestures to dismiss list entries in the sidebar.

**Comment by Mishiranu** [comment]
Swiping gestures aren't good for drawer. Now swiping closes drawer and it's habitually for all apps. I think it's bad idea.
You can also close open pages with X button so swipe is worthless for them.

**Comment by GiRaFa-SM** [comment]
Swiping for the opposite side..

**Comment by Triodan** [comment]
Agreed with the point GiRaFa made. Swipe right opens drawer, another swipe right on a drawer item dismisses it.

**Comment by Mishiranu** [comment]
Even right swipes are not habitual for drawer. I really don't like an idea of swiping to remove elements (some people asked me to make swipe gesture to hide threads), but swipe gesture in drawer is generally overkill.

**Comment by GiRaFa-SM** [comment]
I think this will make the process of removing old/deleted favorites more faster than before. Other thing I want to mention is for add an option to hide the favorites list .. (my lists are very big) sometimes need to go to settings and change some options and scroll a huge list is not very comfortable.

Of course, this is my user experience.

**Comment by libeclipse** [comment]
I agree with this suggestion. It's too much of a hassle to go into the thread you want to remove from favourites and remove it.

Posts expire, and this is an even bigger problem on a big board like /b/. You may only favourite an item for a few minutes to keep track of it while looking at other threads. Currently it's too difficult and not really seamless at all.

**Comment by GiRaFa-SM** [comment]
Sorry for bumping this, but since the only possible way to remove favorite old threads are swiping>long click>remove the thread, it's not possible to make this possible only for favorites threads? The user will need to long click somewhere to enable removing favorite threads by swiping. Or a option to dismiss the action in case of the user make some wrong action. 

And other suggestion.. Can you add an option to hide favorites list? When the list is long takes time to scroll at end of list and go to config or other app section. Thanks.

**Comment by Mishiranu** [comment]
> Swiping gestures aren't good for drawer.

They aren't good even only for favorites.

> Can you add an option to hide favorites list?

There is an update button in favorites header. Also I think it's look afwul too. You need only 1 gesture to scroll to the bottom, moreover it's not often used.

Honestly, I prefer aesthetics more than functionality, so it's not easy to convince me to do something like that. Our russian community on 2ch.hk is already used to it, lol.
