### ISSUE TITLE
2ch.hk recaptcha2 центровка

### ISSUE THREAD

**Issue by shifting-tides** [Mishiranu/Dashchan#242]
при попытке загрузить капчу происходит развертка области капчи за рамками экрана.
Android 10, 423 dp, 1080x2400
При перевороте андроида в полноэкранный режим капча масштабируется нормально.
https://imgur.com/a/AKOEOeR

**Comment by shifting-tides** [comment]
с recaptcha invisible такая же история (в чем отличия, кстати?)

**Comment by Mishiranu** [comment]
Должно быть исправлено в 3.0.2.

> с recaptcha invisible такая же история (в чем отличия, кстати?)

Просто другой вид рекапчи от гугла. Она у них так и называется — invisible.
