### ISSUE TITLE
Кастомный юзер агент.

### ISSUE THREAD

**Issue by lyabra** [Mishiranu/Dashchan#245]
Судя по коммитам ты несколько раз менял юзер агент, почему выбор пал на хромовский виндовый? Можешь дать возможность самому задавать юа?

**Comment by Mishiranu** [comment]
Через продвинутые настройки можно https://github.com/Mishiranu/Dashchan/wiki/Guide-RU

**Comment by Mishiranu** [comment]
> Судя по коммитам ты несколько раз менял юзер агент, почему выбор пал на хромовский виндовый?

На это забыл ответить.

Идея была использовать какой-то популярный юзер агент, который сложно будет заблокировать где-либо. По этой же причине юзерагент каждый раз обновляется при входе в приложение.

Изначально я брал юзер агент файрфокса, но, как оказалось, если ставить его WebView, некоторые сервисы вроде клаудфлары начинают ломаться (видимо, включают какие-то специфичные для файрфокса алгоритмы исходя из юзерагента, а WebView это хромиум всё же). И я решил использовать юзер агент хромиума, всё заработало.

Почему Windows 10? Ну потому что, я думаю, это самая популярная десктопная операционная система.
