### ISSUE TITLE
Быстрое открытие настроек автоскрытия.

### ISSUE THREAD

**Issue by lyabra** [Mishiranu/Dashchan#247]
Добавь в тридот меню пункт для быстрого открытия правил автоскрытия, каждый раз проматывать в настройки ради того чтобы очередной гнилой форс скрыть задалбывает.

**Comment by Mishiranu** [comment]
А быструю кнопку смены темы не хочешь?

Ну серьёзно, куда ещё быстрее?

**Comment by lyabra** [comment]
Темы и так можно менять в тридот меню --> внешний вид, так что с ними проблем не вижу. Когда открыто много тредов список в боковом меню становится очень большим и проматывать в самый низ для открытия настроек рельно задалбывает.
