### ISSUE TITLE
баг в 3.0.1

### ISSUE THREAD

**Issue by Veganch1k** [Mishiranu/Dashchan#248]
при попытке сохранить изображение приложение пытается получить доступ к папке загрузки.
![Screenshot_20200919_103307_com android documentsui](https://user-images.githubusercontent.com/71544306/93661822-9cf17e80-fa63-11ea-9c18-9956db0702f8.jpg)
после нажатия на "предоставить доступ" и подтвеждения разрешения ничего не происходит.
![Screenshot_20200919_103549_com android documentsui](https://user-images.githubusercontent.com/71544306/93661867-096c7d80-fa64-11ea-88cb-565d8583966f.jpg)
и высвечивается следующее сообщение:
![Screenshot_20200919_103623](https://user-images.githubusercontent.com/71544306/93661877-1b4e2080-fa64-11ea-8e7e-b2d9179b5e88.jpg)
повтор этих действий ни к чему не приводит. я не эксперт, но, кажется, SAF работает некорректно.

**Comment by Mishiranu** [comment]
Добавил инструкцию в 3.0.2.
