### ISSUE TITLE
Can you add a default name?

### ISSUE THREAD

**Issue by iloveclover** [Mishiranu/Dashchan#25]
It used to have it but I don't see that option anymore.

**Comment by Mishiranu** [comment]
Yes, I removed this feature in 2.2.0 or 2.3.0. This option was applied to all chans and I thought that it isn't good.
Is it a big problem for you? When you send a post, your name will be saved in draft for this thread as long as client is running.

**Comment by iloveclover** [comment]
I'm fine with it being saved in drafts. I was just asking to see if it was an error.

**Comment by libeclipse** [comment]
There could be a setting added so that users can specify default logins for each Chan that is installed?
