### ISSUE TITLE
Внешний плеер

### ISSUE THREAD

**Issue by Sakurachansky** [Mishiranu/Dashchan#251]
3.0.2 не работает с внешним плеером. Ничего не происходит по клику на видеорилейтед контент

**Comment by Mishiranu** [comment]
Хм, а что должно происходить? Сейчас потыкал — вроде как открывает во внешнем плеере, если встроенный плеер отключён (или не установлены библиотеки).

**Comment by Sakurachansky** [comment]
Кликаю на вебм/мп4 и ничего не происходит. Установлен мх плеер и мпв.

**Comment by Mishiranu** [comment]
Зайди в настройки системы → Applications → Dashchan for 2ch.hk → Open by default → Clear defaults.
