### ISSUE TITLE
There isn't a "Share" button

### ISSUE THREAD

**Issue by darlopvil** [Mishiranu/Dashchan#252]
Hi, 

I don't know if this was questioned here before, but I think It would be a good idea to implement a Share button when opening a thread. Personally, I find it quite useful to share some good content with friends via WhatsApp or other external apps.

Maybe this has to be asked in the Dashchan Extensions git page. If so, please delete this issue and reconsider my idea again, 

thanks.

**Comment by Mishiranu** [comment]
You can use long tap on the post to share the post. Sharing original post effectively works as sharing a thread.

**Comment by darlopvil** [comment]
Oh, thanks, Didn't see it!
