### ISSUE TITLE
Changelog doesn't show up

### ISSUE THREAD

**Issue by darlopvil** [Mishiranu/Dashchan#253]
Hello,

I don't know if this was previously mentioned here, or at least, in Russian, but once you want to check the log or historical of what are the new enhancements or fixed things on a new version of the app, It just doesn't appear. After 2-3 seconds of a "Loading" small dialog box, an "Unknown error" message is displayed.

I thought this would have been corrected in next updates, but it doesn't seem to be. Is there something in particular for this?
Thanks.

**Comment by Mishiranu** [comment]
Which locale do you use? I mean system setting. Did you change it in application?

**Comment by darlopvil** [comment]
Do you mean if I've changed the deafult configuration of the app? In that case, yes, of course. Not only the default youtsuba theme, but some other things as the download directory or the refresh interval.

If you mean my OS, that would be Android 8.1.0

**Comment by Mishiranu** [comment]
I mean the system language. And application language as well (if changed from "System").

**Comment by darlopvil** [comment]
I've fixed it! It was just like you said, go to "Languages" and change the "Deafult" option to "English". Now It works perfectly. Many thanks~

**Comment by Mishiranu** [comment]
I still think it's a bug. What's your system language?

**Comment by darlopvil** [comment]
spanish

**Comment by Mishiranu** [comment]
Found the problem. Should be fixed in next release.

**Comment by darlopvil** [comment]
What was the problem, only for curiosity.

**Comment by Mishiranu** [comment]
I didn't try to fallback to English language if no changelog for your system locales available. Currently they're available in English and Russian, and I doubt it will change. Client just supports downloading changelog in any language.
