### ISSUE TITLE
Закрытие цепочки ответов с жестами

### ISSUE THREAD

**Issue by CryingUnicorn** [Mishiranu/Dashchan#257]
Запили, пожалуйста, закрытие цепочки ответов каким-нибудь свайпом вниз, например, а то используя жесты совсем не прикольно тыркать на экран по двести раз, чтобы закрыть все ответы

**Comment by Mishiranu** [comment]
Хорошая идея, но я всё же думаю, что вертикальные жесты будут сбивать толку, ведь у окна ответов вертикальная прокрутка.

Думаю попробовать горизонтальные, но мне всё ещё не нравится идея, что свайпом можно закрыть всю цепочку, а делать что-то вроде закрытия цепочки свайпом влево или только одного ответа свайпом вправо тоже немного неочевидно.

Постараюсь до следующего обновления что-нибудь придумать.

**Comment by Mishiranu** [comment]
В итоге я решил сделать вертикальные жесты, будет доступно в следующем релизе.

![device-2020-11-11-000321](https://user-images.githubusercontent.com/8524113/98735578-826cbf00-239b-11eb-8972-57ebec8481ce.gif)
