### ISSUE TITLE
добавление функционала скрытия 

### ISSUE THREAD

**Issue by shifting-tides** [Mishiranu/Dashchan#259]
добавить возможность скрытия постов по названию прикрепленных файлов до символа/целиком;

CASDU
CASD*

**Comment by Mishiranu** [comment]
Ну я вряд ли буду что-то там с символами особенно мудрить, текущая функциональность скрытия работает через регулярные выражения, я думаю, с ними же и будет работать, просто ещё одна галочка в правилах появится.

Скрытие будет работать только для файлов с оригинальным названием (не на всех сайтах бывает), а не по названию, сгенерированному сервером.

**Comment by Mishiranu** [comment]
Сделано в 3.1.0.
