### ISSUE TITLE
Can't write to SD card (external) even allowing the app to write 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#26]
Phone model: Galaxy S4 GT-i9505 - ROM JDCT ROM 6.0.

**Comment by Mishiranu** [comment]
I know about this problem. It's a system restriction: since 4.4 apps can't access external SD card, only internal memory.

**Comment by GiRaFa-SM** [comment]
Me too, but I was using JDCT 5.1.1 and your app was working perfectly when I tried to record any file to SD card... 

So there is nothing you could do? 
I'll downgrade to 5.1.1 then... Waiting to your reply to close this issue.

**Comment by Mishiranu** [comment]
This restriction could be disabled by fixing some files in /system dir. Some custom rooms do this by default (CM, for example).

**Comment by GiRaFa-SM** [comment]
Well.. In JDCT ROM they don't tweaked this. Even if I edit some XML related to this, the sd card doesn't works. 

Back to 5.1.1 then... 6.0, maybe next year. 
Thank you for your support Mishiranu. I'll close this issue.

**Comment by GiRaFa-SM** [comment]
Devs fixed this issue on JDCT 6.0, so isn't a problem with the app.
