### ISSUE TITLE
краш приложения при открытии видео

### ISSUE THREAD

**Issue by shifting-tides** [Mishiranu/Dashchan#260]
дропаются фреймы при проигрывании видео, моментальный краш после нажатия на техническую информацию и краш на 2-3 секунде ролика. 

крашился подобным образом уже несколько раз, могу собрать больше примеров для репликации.
Android 10

**Comment by Mishiranu** [comment]
Да, действительно крашится на 3.0.4.

Но я на самом деле вносил довольно большое количество правок в плеер (сильно изменилась техника загрузки самих файлов, к тому же я обновил библиотеку с ffmpeg), и на моей девелоперской версии уже никаких вылетов нет.

Думаю, подобные вопросы с плеером лучше будет оставить до следующего релиза уже.

**Comment by Mishiranu** [comment]
Ну, вроде на том видео больше не крашится теперь.
