### ISSUE TITLE
Запили воспроизведение видосов в фоне, молю!! 

### ISSUE THREAD

**Issue by dvoyakiy** [Mishiranu/Dashchan#264]
Часто хочется включить музыку из музыкального вебм треда и уйти в другое приложение. Но в фоне не играет... А хотелось бы.

**Comment by rss-2013** [comment]
Поддерживаю.

ср, 18 нояб. 2020 г., 00:16 dvoyakiy <notifications@github.com>:

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/issues/191

**Comment by kotoshii** [comment]
@Mishiranu значит ли эта активность, что в скором времени можно будет увидеть эту функциональность в приложении?

**Comment by Mishiranu** [comment]
Не, просто проходился по issue и смотрел, что закрыть, а что нет.

**Comment by kotoshii** [comment]
> Не, просто проходился по issue и смотрел, что закрыть, а что нет.

Понял, жаль. Будем ждать.

**Comment by kotoshii** [comment]
@Mishiranu
Привет, есть ли вероятность, что эта фича когда нибудь появится в приложении?
