### ISSUE TITLE
iichan.hk - крашится приложение

### ISSUE THREAD

**Issue by Alepod** [Mishiranu/Dashchan#265]
При попытке открыть любой тред или доску на iichan.hk либо "некорректный ответ сервера", либо попросту вылетает приложение. Иные борды работают.
Android 5.1

**Comment by Mishiranu** [comment]
А лог можно?

**Comment by Alepod** [comment]
Где он сохраняется?

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/wiki/Home-RU#Решение-проблем

**Comment by Alepod** [comment]
Лог в папке не был сохранён.

**Comment by Alepod** [comment]
UPD: В новых обновлениях клиента и расширения проблема решена. Спасибо!

**Comment by Mishiranu** [comment]
Вряд ли это проблема с расширением была, ну ладно.
