### ISSUE TITLE
Floating button for creating new threads 

### ISSUE THREAD

**Issue by jkrass1** [Mishiranu/Dashchan#266]
Like this 
![IMG_20201123_113543](https://user-images.githubusercontent.com/9212851/99942182-431d7580-2d80-11eb-9ac8-30bb044e1fb2.jpg)

It is hard to reach top bar

**Comment by Mishiranu** [comment]
This will need a rework so the button didn't overlap threads at the bottom. I also don't like FAB pattern, and actually I doubt anyone makes new threads this often to find it annoying.

**Comment by Sakurachansky** [comment]
> This will need a rework so the button didn't overlap threads at the bottom. I also don't like FAB pattern, and actually I doubt anyone makes new threads this often to find it annoying.

Двачую.

**Comment by jkrass1** [comment]
> This will need a rework so the button didn't overlap threads at the bottom. I also don't like FAB pattern, and actually I doubt anyone makes new threads this often to find it annoying.

Forgot to mention, it also should create new posts 
Very handy rather than trying to reach the top panel

**Comment by Mishiranu** [comment]
I suppose "reply to post" is used more often than just replying to a thread. This is done by long tap on post which should be easier than using the button at the top.
