### ISSUE TITLE
Автоматизированное решение голосовой капчи

### ISSUE THREAD

**Issue by shifting-tides** [Mishiranu/Dashchan#267]
Возможна ли интеграция https://github.com/dessant/buster для решения капчи?
Задоначу, если данная фича появится.

**Comment by Mishiranu** [comment]
А нельзя ли через какой-нибудь Bromite это делать? Я, впрочем, не помню, есть ли у них поддержка аддонов, тем более для WebView.

**Comment by shifting-tides** [comment]
увидел - предложил. сгодится любой автосолв капчи
