### ISSUE TITLE
Клиент падает при попытку скопироватб или цитировать.

### ISSUE THREAD

**Issue by mdilai** [Mishiranu/Dashchan#27]
Началось пару мажорных апдейиов назад уже несколько месяцев. Одинаково как на планшете с Android 5.0.2 (не обновлял с апреля) так и на телефоне со свежим 6.0.1 и factory reset. Как повторить - виделить любой текст и нажать кнопку копировать или цитировать и приложение сразу падает. Каждый раз. Приаттачил лог креша
[error-1450555480286.txt](https://github.com/Mishiranu/Dashchan/files/67593/error-1450555480286.txt)

**Comment by Mishiranu** [comment]
Странная ошибка, похоже на какой-то системный баг или что-то вроде того.
Попробуй поставь https://www.dropbox.com/s/dc28egqgl8conw0/Dashchan_ctest.apk и скажи, перестало ли вылетать.

**Comment by mdilai** [comment]
Да, помогло, тестовая версия не вылетает.

**Comment by Mishiranu** [comment]
Тогда так и оставлю. Пока пользуйся этой версией, она ничем не отличается от обычной 2.4.3, кроме этого исправления.

**Comment by GiRaFa-SM** [comment]
I forgot that Mishiranu is a Russian dev lol.

**Comment by mdilai** [comment]
I really surpirsed that DashChan is popular somewhere outside russian imageboard 2ch.hk

**Comment by GiRaFa-SM** [comment]
I aways comment on topics about 4chan apps for everyone give a look on dashchan. Look how many sites this APP support.

The best 4chan APP(and many others sites i know).
