### ISSUE TITLE
What program do you use to create extensions?

### ISSUE THREAD

**Issue by kira2022** [Mishiranu/Dashchan#271]
I want change and adapt an extension that has already been created in a faster and more efficient way. For example, if I want to rename "chan.extension.name" for all java files, how do I do this? Another question: when I manage (with a lot of effort, because I edit all files manually) to change an extension and make it work, the list of boards does not appear, it returns "empty answer". How to solve?

**Comment by Mishiranu** [comment]
> in a faster and more efficient way

Just get the source code and adapt it for your needs. All extensions are hosted here https://github.com/Mishiranu/Dashchan-Extensions.

> What program

Personally I use Intellij IDEA, because I need debugger and other development stuff. If you don't need, you can just use terminal emulator and text editor.

> the list of boards does not appear

It depends.

**Comment by kira2022** [comment]
> Personally I use Intellij IDEA, because I need debugger and other development stuff. If you don't need, you can just use terminal emulator and text editor.

Thank you, I will try this program. Please, one last question: what tool do you recommend for creating a drawable vector? I don't want to draw from the beginning, I just want to transform an image into a vector drawing. I need to change this to the extent I intend to adapt.

**Comment by Mishiranu** [comment]
I use Inkscape. It also has "trace bitmap" feature which allows to convert raster images to vector images, but it should be used carefully.

**Comment by kira2022** [comment]
> Eu uso o Inkscape. Ele também possui o recurso "trace bitmap" que permite converter imagens raster em imagens vetoriais, mas deve ser usado com cuidado.

Obrigado!

**Comment by kira2022** [comment]
> Eu uso o Inkscape. Ele também possui o recurso "trace bitmap" que permite converter imagens raster em imagens vetoriais, mas deve ser usado com cuidado.

Thanks!
