### ISSUE TITLE
Select custom flags on /pol/

### ISSUE THREAD

**Issue by tjoAU** [Mishiranu/Dashchan#272]
Recently the app got the ability to display custom flags, but you still can't select it. The 4chan API accepts a 2 letter code in the form  field "flag" that gets sent to post on /pol/. The 4chan [board API](https://a.4cdn.org/boards.json) has a board attribute "troll_flags" that will be set to 1 on boards that have them (currently only /pol/) and a list of flags and their codes at the end also under the name "troll_flags", so these could probably be put into a spinner or something.

**Comment by Mishiranu** [comment]
You can. But you need to refresh the boards list to reload config.

**Comment by tjoAU** [comment]
My bad, didn't realise
