### ISSUE TITLE
Кнопка "Сохранить" не всегда появляется (медиа)

### ISSUE THREAD

**Issue by IS2511** [Mishiranu/Dashchan#277]
Проблема при перелистывание на следующую медиа, в основном легкие видео. Кнопка "Сохранить" появляется только после перелистывание на любую соседнюю медиа и обратно + плэй. Не всегда такое происходит, но часто

"Загружать ближайшие изображения" грузит маленькие видео и не репортит, что кэш есть? Видео кэшируется так быстро, что проверка на возможность "скачивания" не срабатывает? Не детектится полная загрузка видео в кэш?

**Comment by Mishiranu** [comment]
> Проблема при перелистывание на следующую медиа, в основном легкие видео. Кнопка "Сохранить" появляется только после перелистывание на любую соседнюю медиа и обратно + плэй. Не всегда такое происходит, но часто

Не понятно, что происходит, можно видео?

> "Загружать ближайшие изображения" грузит маленькие видео

Эта функция только с картинками работает.

**Comment by IS2511** [comment]
Пример отсутствия кнопки "Сохранить":
https://files.catbox.moe/1w44xc.mp4

**Comment by Mishiranu** [comment]
Ага, на 11 секунде. Вижу.

**Comment by ousennin** [comment]
Вот пулл-реквест с фиксом - https://github.com/Mishiranu/Dashchan/pull/280 . Возможно, фикс не очень красивый, зато работает.
