### ISSUE TITLE
Batch saving with the full name of the topic/thread 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#28]
Just improvement. In the past I requested a feature for adding more options to save images and saving images with the thread name... Sometimes the app doesn't create the folder with the full thread title and I have to rename manually. It's possible to improve this? Or exists an limitation of the number of characters you can use?

**Comment by Mishiranu** [comment]
Thread title is truncated to the first 30 characters.

**Comment by GiRaFa-SM** [comment]
A question, in my phone appears the directory three when I try to save something and the save dialog appears... That counts as characters too? You can't make possible to put more characters? Thank you.

**Comment by Mishiranu** [comment]
Only thread title characters are counter, not all path, if I understand you.
I think 30 characters is enough for directory name. I can make ~50, but does it decide something?

**Comment by GiRaFa-SM** [comment]
Hahaha, that's because sometimes I'm too lazy to rename manually sometimes. And some anon make topics with giant titles. I would appreciate if you include in the next update. 

Sorry for my English, it's very limited because I don't know some English words. Thank you for your attention.

**Comment by Mishiranu** [comment]
Ok, next version I'll make 50 chars.

> Sorry for my English, it's very limited because I don't know some English words. Thank you for your attention.

Lol, mine isn't good too.

**Comment by GiRaFa-SM** [comment]
Closing this issue because I realized That the now the app is creating folders with more characters. 

Tbh your English is better than mine and very understandable. But some grammar rules really fuck up everything and are hard to get used to it.
