### ISSUE TITLE
Где загрузить бинарники расширений?

### ISSUE THREAD

**Issue by veronikazaglotova** [Mishiranu/Dashchan#283]
Я наверное бака извините но здесь раньше была таблица и кнопочки как загрузить :/

**Comment by Mishiranu** [comment]
Таблица и сейчас есть, просто переехала https://github.com/Mishiranu/Dashchan-Meta
А вообще, прямо из приложения можно.

**Comment by veronikazaglotova** [comment]
Спосибо я уже пони
