### ISSUE TITLE
Go to next post that contains a (You)

### ISSUE THREAD

**Issue by veronikazaglotova** [Mishiranu/Dashchan#287]
f77/Dashchan-Continued had arrows at the top of the screen, they were useful to me...

**Comment by Mishiranu** [comment]
You can search by ":r".

**Comment by veronikazaglotova** [comment]
It's not as /comfy/ IMO

**Comment by veronikazaglotova** [comment]
@Mishiranu 
I may be dumb but is this how I'm supposed to use it?
![Screenshot_20210119-232459](https://user-images.githubusercontent.com/52463107/105070558-ad674380-5aad-11eb-9805-2ded7f120f7d.jpg)

**Comment by Mishiranu** [comment]
You'll need to enable advanced search in settings.
