### ISSUE TITLE
Preview posts from other threads

### ISSUE THREAD

**Issue by veronikazaglotova** [Mishiranu/Dashchan#288]
On 2ch, when you tap on a quote of a post from a different thread, you can immediately see the post
![Screenshot_20210117-151849](https://user-images.githubusercontent.com/52463107/104836354-97078f00-58d7-11eb-9e7c-a301da0f1c35.jpg)
On 4chin, it opens "Open thread?" dialogue and I'm forced to open that thread to see the post.
![Screenshot_20210117-151835](https://user-images.githubusercontent.com/52463107/104836369-b0104000-58d7-11eb-86f0-d286b9e19ab9.jpg)

**Comment by Mishiranu** [comment]
Это потому что не все борды имеют функциональность получения одного поста по его номеру.
