### ISSUE TITLE
(You) notificafion

### ISSUE THREAD

**Issue by iloveclover** [Mishiranu/Dashchan#3]
Can you add some sort of way to show that someone replied to you? Thank you very much. Oh, and I use the 4chan extension mainly.

**Comment by Mishiranu** [comment]
Most imageboards don't provide number of post that just been sent. Only 4chan and some other sites can do this. Maybe I'll think about this exclusive feature for them later.

**Comment by GiRaFa-SM** [comment]
This function is the water divisor for many chan users on Mobile.
If the dev add the feature mentioned a above and publish on GP this app will be a 4chan App Killer imo.
