### ISSUE TITLE
No [code/math/spoiler] tags

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#30]
[code/math/spoiler] tags need to be added on /g/, /sci/, and everywhere else, respectively.

**Comment by Mishiranu** [comment]
Are you talking about 4chan? Code and spoiler tags are both exists. But math is exclusive 4chan tag for folmulas. It's hard to implement theirs displaying (if it even possible for default android TextView).

**Comment by libeclipse** [comment]
Yes, I'm talking about 4chan. A font could be installed with it for mathematical symbols, and JS used to implement it.

**Comment by libeclipse** [comment]
All the mathematical symbols are available in unicode. Although they can't just be used like that if you're planning on proper formatting.

**Comment by Mishiranu** [comment]
As I told, it's hard to implement it because I need tex parser for this. I don't want to overload the app with supporting these unique features for some imageboards, especially if these features are so complicated.

**Comment by libeclipse** [comment]
This might be useful.

https://www.mathjax.org

**Comment by Mishiranu** [comment]
I have an idea. I can replace [math] tags with image links. Clicking on them will open a gallery window with rendered formula.
I found a [web service](http://quicklatex.com/) that can render images using latex markup.

**Comment by Mishiranu** [comment]
Also it was rather a question to you. Does this solution suit you?

**Comment by libeclipse** [comment]
So functionality you click on the tag and it opens in a browser? It's not optimal but it's better than nothing.

I found a few libraries for it, but you probably don't want extra dependencies. 

https://github.com/opencollab/jlatexmath
http://stackoverflow.com/questions/456002/displaying-fancy-equations-with-java

**Comment by Mishiranu** [comment]
> So functionally you click on the tag and it opens in a browser?

In image viewer, not in browser.

**Comment by libeclipse** [comment]
I guess that's usable.

**Comment by Mishiranu** [comment]
Added in new extension update.

It's disabled by default, you can enable it in extension settings (Settings — Forums — 4chan.org).

Also maybe you'll need to reload some old threads (Menu — Thread options — Reload)

**Comment by libeclipse** [comment]
Niiice.
