### ISSUE TITLE
Copy posts but only what it's needed.

### ISSUE THREAD

**Issue by darlopvil** [Mishiranu/Dashchan#301]
Hi,

Although you can copy the text of a post, it won't work if you only want to copy the same words or phrases of a post. I think it would be a nice detail, since non-english natives tend to copy and search words they don't know in dictionaries.

**Comment by Mishiranu** [comment]
You can use double tap to select the text. Is it what you need?

**Comment by darlopvil** [comment]
It could do the trick, but it could be like this too: Long tap on the post> the word under your finger gets selected> Now you can freely select more words/what you need. I mean, it doesn't have to be a double tap but the idea would be this.

**Comment by Mishiranu** [comment]
> It could do the trick

*can

Dashchan works like this for years. Have you tried it?

**Comment by darlopvil** [comment]
>Double tap gives you all the text selected
>Manually, choose the word you're interested. 
it's fine, but it would be faster and more practical to double tap on a word and have it already selected (instead of having all the text selected)

**Comment by Mishiranu** [comment]
> Double tap gives you all the text selected

It depends. It can either select the whole post or only a single paragraph depending on how you click. This use case is much more frequent than selecting a single word.

**Comment by darlopvil** [comment]
As you wish. If you want to leave what exists, i'll get used to it. If not, it would be appreciated.
