### ISSUE TITLE
webms can't attached anymore

### ISSUE THREAD

**Issue by krautbernd** [Mishiranu/Dashchan#302]
still working with 3.0.2

using my kc extension
https://github.com/krautbernd/Dashchan-Extensions-kohlchan

**Comment by Mishiranu** [comment]
Works for me.

Which Android version? What does "cant be attached" mean?

**Comment by krautbernd** [comment]
Android 11

![IMG_20210709_154918](https://user-images.githubusercontent.com/39069188/125088019-50982d80-e0cd-11eb-8067-644af950b8d9.jpg)

just found out, it only happens when picking the webm/videofile via f-stop gallery. google pics and androids common filepicker working fine.

**Comment by Mishiranu** [comment]
Just checked F-Stop Gallery. It's broken.

https://developer.android.com/reference/android/provider/OpenableColumns

> These are standard columns for openable URIs. Providers that serve openable URIs **must** support at least these columns when queried.

They don't support `_size` column, this is a violation which breaks Dashchan. You'll better to contact F-Stop Gallery developers and ask them to fix it.

**Comment by krautbernd** [comment]
thank you.

i contacted them. lets wait and see 🙂
