### ISSUE TITLE
Make it harder to swipe to next image.

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#31]
A constant problem that I have is that when I'm zooming into images, it's way too easy to swipe to the next image.

An easy solution is to not swipe to the next image when zoomed in.

**Comment by Mishiranu** [comment]
There was a gallery bug in last version (honestly, this bug exists a long time). I fixed it a week ago, so I think in next version scaling won't cause swiping image.

**Comment by Mishiranu** [comment]
Try it in last version. Is it work better?

**Comment by libeclipse** [comment]
Ah, that's a nice solution to the problem. Still allowing swiping but making accidental swiping harder. Cleaner solution than clover.

**Comment by Mishiranu** [comment]
I don't made it harder. I fixed a bug. For example, in previous version you could tap with two fingers, release them and app determined it as a swipe. I fixed it and accidential swipes have gone too.
