### ISSUE TITLE
Clean installed and can't do much.

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#32]
I clean installed the Main .apk, 4chan apk, and the WebM apk.

Now, I can't change the theme or open any images. Latest versions installed as of this moment.

**Comment by Mishiranu** [comment]
It was my mistake, but I fixed it in a hour after updating and reuploaded an apk without changing version code. Open updating screen, choose "Release" branch for client and download it again.

**Comment by libeclipse** [comment]
Ah, works now. Thank you.
