### ISSUE TITLE
Captchas not rendering properly.

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#34]
When I try to reply, I load the captcha and this is how it appears:

http://i.imgur.com/Kgkbn1z.png

I can't see nor click the images. Don't mind the red hue, it's just Twilight.

**Comment by Mishiranu** [comment]
It was changed again. I'll fix it later. Just use old recaptha instead, it's easier.

**Comment by Mishiranu** [comment]
Fixed in last update.
