### ISSUE TITLE
Improve WebM player and listing 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#35]
Thank you for adding WebM support, now I don't need to open MXPlayer aways when I want to see an WebM. 

But I noticed one thing. 

When you click in an photo in the gallery, after you press the back button, the app shows the part that this picture is located and his specific post. But that doesn't happen when you click on an WebM in the gallery. 

Can you make the WebM player background dim? Like when you click on a picture. 

I've had the same bugs I had on MXPlayer. So I believe that this extension is almost perfect. Thank you so much.

**Comment by Mishiranu** [comment]
What listing are you talking about?

I think an opaque background is better for video player window (gallery and video player are separate windows).

**Comment by GiRaFa-SM** [comment]
Option "scroll thread when scroll gallery". It doesn't works with WebM.

**Comment by GiRaFa-SM** [comment]
I forgot to say.. Is possible to add an option to loop WebM? (or make it by default)

**Comment by GiRaFa-SM** [comment]
Bug, when I open the app and try load an WebM, the app redirect it to an external player,  seems that the app doesn't detect the WebM plugin and ask to open in an external app.

**Comment by Mishiranu** [comment]
> Option "scroll thread when scroll gallery". It doesn't works with WebM. 

I'll fix it.

> I forgot to say.. Is possible to add an option to loop WebM? (or make it by default)

In preferences: Action on playback completion — Play again.

> Bug, when I open the app and try load an WebM, the app redirect it to an external player, seems that the app doesn't detect the WebM plugin and ask to open in an external app.

Have you enabled player in preferences?

**Comment by GiRaFa-SM** [comment]
Are you a genius or something? When Russians want to do something, they really give their best. 

Solid Explorer devs and you made awesome apps.  

Thank you for your support and replying stupid questions.

**Comment by Mishiranu** [comment]
Sorry, I've forgotten about your bug. I'll fix it in next version.

**Comment by GiRaFa-SM** [comment]
Isn't a bug tbh, just a improvement. It's just a idea, but what about you visit 4chan someday and make a post about your app, if you have time. I've seen Clover dev posting in many topics and some anons talking about your app. It will be nice.

**Comment by Mishiranu** [comment]
I often visit 4chan but doesn't promote my app. Sometimes I answer to questions about dashchan.

**Comment by GiRaFa-SM** [comment]
It's not only about to promote it, it's to hear users and new ideas... 
With anonymous profile?

**Comment by Mishiranu** [comment]
Too hard for me. I've already have a thread in russian 2ch.hk, so it would be harder to make a threads and maintain a support in one more forum.

> With anonymous profile?

Yes.

**Comment by GiRaFa-SM** [comment]
Fixed in the last version, closing this issue.
