### ISSUE TITLE
Simple or (not) stupid questions 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#36]
Well, I've been using Dashchan for a long time and now is my favorite app to browse 4chan. I bought Mimi4ChanReader in the past and the developer became lazy and ruined his app completely when he updated his app to Material version, I suggested many things to make Mimi better but until today only some features was completed. Compared with Mishiranu this app have more active support and better implemented features, and many chans added. 
Sorry for this wall of text. 

But asking, I have some doubts of how Archive Threads work, I save many topics to see after some time but Wtf, I'm too tired to save all content and read all the posts on it in just 7 days (the time limit that 4chan archive topics to desustorage.org). I have more than 100 topics to save images.. 

If I archive topics I can see the content save whenever I want? I really need to save thumbnails? 

If I want do delete pics I don't want, I'll need to go to my storage and delete them manually? 

If I "save" an image on topic I archived this pic will be duplicated or moved to 4chan folder? 

If I remove from the FAV lists, the topic archived will be deleted on my SD card? 

I saw a option when I was browsing desustorage.org named "see the original) its possible to make the opposite, if the topic is already archived on desustorage.org? Mainly if the topic I want to visit is already archived in desustorage.org. 

When the thread is closed, and I browse my pc I have to visit 4chan.org/a/archive (or something like like that), asking, this app loads threads on this page? If yes, is possible to make an option to see what topics are archived on 4chan.org/a/archive? 

I'm a Faggot? Jokes aside, thank you again for this app. Sorry for this wall of text.

**Comment by GiRaFa-SM** [comment]
Tested(offline) : I can read all the text on the thread, but when I click on a pic it says, unable to download data, when with the pic saved on my SD Card, or its the manner of the archive option is supposed to work?

**Comment by Mishiranu** [comment]
Archiving save threads in HTML format in Archive folder. All files are downloaded to this folder with HTML file of thread, and this feature doesn't intersect with downloading files. So if you download a file, it won't show in local archive. Just open Archive folder and look for it's structure.

> If I archive topics I can see the content save whenever I want? I really need to save thumbnails?

No, you need to save only what you want. If you save thumbnails, they will be shown in local archive obviously.

> If I want do delete pics I don't want, I'll need to go to my storage and delete them manually? 

Yes, you are right.

> If I "save" an image on topic I archived this pic will be duplicated or moved to 4chan folder? 

It will be duplicated.

> If I remove from the FAV lists, the topic archived will be deleted on my SD card? 

No. Have you downloaded the local archive extension?

> I saw a option when I was browsing desustorage.org named "see the original) its possible to make the opposite, if the topic is already archived on desustorage.org? Mainly if the topic I want to visit is already archived in desustorage.org.

No, it's not possible. I think about this feature later.
Now you can open desustorage and type "g 12345678" or something like that in "Code, number, URL" field to navigate to archived thread fast.

> When the thread is closed, and I browse my pc I have to visit 4chan.org/a/archive (or something like like that), asking, this app loads threads on this page? If yes, is possible to make an option to see what topics are archived on 4chan.org/a/archive?

I don't really understand you, but you can view a list of archived threads in Menu — Archive.

**Comment by GiRaFa-SM** [comment]
I really need give a look better in the applications I use, really. 

No, I download the extension in the past my I didn't know how this extension is supposed to work.

About desustorage.org, you said "I'll think about this feature later". After this you said it wasn't possible, you already checked it? 

You clarified everything, thank you so much. This isn't really a issue, tough.

**Comment by Mishiranu** [comment]
> No, I download the extension in the past my I didn't know how this extension is supposed to work.

This extension used for reading the local archived threads. It named "localhost" in extensions list.

> About desustorage.org, you said "I'll think about this feature later". After this you said it wasn't possible, you already checked it?

I said it before, not after. Now it's impossible, but I can think about it and add a support later.

> Maybe this is a feature request, but is possible save archives files with their original filenames? 

No, it's not so easy as you think. But maybe later I'll add original file name in HTML, it seems I forgot about it.

**Comment by GiRaFa-SM** [comment]
I download the extension. Works pretty well. The only board I download files with their original filenames is /a/. It's because I've seen some anons refusing giving sources because the filename shows that information. If I archive the the thread without their original filenames I can't get that info faster. BTW I think I can find it using reverse search engine. 


I was thinking, again, is possible to choose between:

Original filenames 
Detailed filenames 
Board filenames when archiving? Thank you so much again for replying my questions. 

On the 2chan everyone posts in Russian isn't it? :( I can't comment there, it seems.

**Comment by Mishiranu** [comment]
> I was thinking, again, is possible to choose between:

It's not so easy as you think. Now local archive makes a clone of current thread, so I think saving server file names is the most correct. In HTML you can see original name, also you can see it via local archive extension.

> On the 2chan everyone posts in Russian isn't it? :( I can't comment there, it seems. 

Yes. Forget it, just post here, lol.

**Comment by GiRaFa-SM** [comment]
OK, so in the future when I have more lazy and crazy ideas I'll post them here. I just checked the HTML file and I don't seen the original filename before the file be posted on the image board.. BTW you said you'll add original filenames on HTML files in the future... Thank you for your support.
