### ISSUE TITLE
4chan Pass?

### ISSUE THREAD

**Issue by Xyllon** [Mishiranu/Dashchan#37]
Hi, I was just wondering if there is or will be support for 4chan passes.

**Comment by GiRaFa-SM** [comment]
I don't have an 4chan pass but I was wondering about this too.

**Comment by Mishiranu** [comment]
I can implement it if you give me one.

**Comment by Xyllon** [comment]
I'll email you my one that you can use for this.

**Comment by Mishiranu** [comment]
Ok, I've implemented id. Download the latest extension and check it.

**Comment by Xyllon** [comment]
Cool, works, thanks.
