### ISSUE TITLE
Can you add 02ch.in support?

### ISSUE THREAD

**Issue by wakaber** [Mishiranu/Dashchan#39]
API - https://02ch.in/faq

**Comment by Mishiranu** [comment]
Думаю, можно попробовать.

**Comment by Mishiranu** [comment]
В апи какая-то ошибка.

Если я запрашиваю https://02ch.in/a/api/post?id=32317, то внизу страницы появляются лишние заголовки и контент:

```
Cache-Control: no-cache, no-store, must-revalidate
Expires: Mon, 12 Apr 1997 05:00:00 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *

{
   "error" : "Unknown json parameter.",
   "code" : 500
}
```

Я, конечно, смогу такое предусмотреть, но вам стоило бы это исправить.

**Comment by wakaber** [comment]
Вроде пофиксила, thanks за обнаружение бага :D

**Comment by Mishiranu** [comment]
Раз такие дела, можно ещё фичреквест небольшой?
Было бы хорошо, если бы был запрос к апи такого вида:
`/board/api/count?id=thread`
Возвращает количество постов в треде (также в json в отдельном поле для этого). Если тред не существует - ошибку в status, как для остальных запросов.
Было бы очень хорошо такое иметь для трекера постов.

**Comment by wakaber** [comment]
Сейчас запилю.

**Comment by wakaber** [comment]
Готово
    /board/api/postcount?id=n

**Comment by Mishiranu** [comment]
Ага, благордарю.
Ещё в d у постов есть айдишники (`Аноним ID: 7EzVirsK`), а в апи их нет. Их тоже бы желательно добавить наверное.

**Comment by wakaber** [comment]
Добавлено. поле 'id'

**Comment by Mishiranu** [comment]
Кстати, `postcount` выдаёт на 1 меньше, чем реальное количество постов. Но можно и так оставить, конечно.

**Comment by wakaber** [comment]
Вроде правильно, или надо чтобы оп-пост тоже считал?

**Comment by Mishiranu** [comment]
Не обязательно, если так и задумано — то пускай остаётся.

**Comment by wakaber** [comment]
Не, функция за 5 минут была написана. Теперь по дефолту отдает кол-во с оп-постом, чтобы его не было надо добавить параметр no_op к реквесту с любым значением (1/true/etc).

**Comment by Mishiranu** [comment]
Готово https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanNulldvachin.apk

**Comment by wakaber** [comment]
Благодарю.

**Comment by wakaber** [comment]
Немного допилила api, в boardinfo теперь это
      "boardinfo" : {
         "board_name" : "Аниме",
         "config" : {
            "posting_allowed" : "1",
            "image_op" : 1, // создание тредов с пикчами
            "captcha" : 0,
            "max_res" : 500, // бамплимит
            "max_files" : 4,
            "names_allowed" : 1, // может быть 1, даже если отключено в конфиге (если есть печенька с "leet" трипкодом), проверяется на стороне сервера
            "image_replies" : 1 // ответ с пикчами
         },
         "board_desc" : "Чятик для двоих",
         "board" : "a"
      },

**Comment by Mishiranu** [comment]
`captcha` — сейчас я её определяю запрашивая html страницу доски при создании поста. Теперь можно считывать json доски, но это по-прежнему не очень удобно. Было бы лучше, если бы это можно было сделать одним запросом вроде `/board/api/checkcaptcha`, чтобы быстро определить, надо ли грузить капчу или отображать "вам не нужно вводить капчу".

`image_replies` — а это для чего? Это просто определяет возможность постить пикчи? Меня именно "ответ" смущает, возможно ли такое, что при ответе нельзя прикреплять, а при создании треда — можно?

А так кое-что пригодится, потом как-нибудь добавлю.

**Comment by wakaber** [comment]
Хм, а если такого вида запрос будет?
`/brd/api/checkconfig`
```
{
   "board_name" : "Аниме",
   "config" : {
      "image_op" : 1,
      "posting_allowed" : "1",
      "names_allowed" : 1,
      "captcha" : 0,
      "max_res" : 500,
      "max_files" : 4,
      "image_replies" : 1
   },
   "board_desc" : "Чятик для двоих",
   "board" : "a"
}
```
Отдает всего около 500 байт, можно чекать по obj.config.captcha. Или все же лучше сделать только checkcaptcha, который будет отдавать значения 0/1?

`image_replies` — да, возможно, но пока мне не приходилось это использовать.

**Comment by wakaber** [comment]
В общем сделала так
`/board/api/checkconfig` - отдает полный boardconfig
`/board/api/checkconfig?captcha=y` - отдает только `{ captcha: val }`

**Comment by Mishiranu** [comment]
> Хм, а если такого вида запрос будет?

Да, так нормально будет.

**Comment by Mishiranu** [comment]
Обновил с учётом нового апи.
Кстати, исходник модуля [здесь](https://github.com/Mishiranu/DashchanNulldvachin) лежит.

**Comment by wakaber** [comment]
Спасибо.
Ok
