### ISSUE TITLE
Notify on (You)

### ISSUE THREAD

**Issue by ghost** [Mishiranu/Dashchan#40]
Now that your own posts are marked, it'd be cool if there were some notice that you'd been replied to.

Either a standard Android notification or a different color on the new post square in the thread drawer.

**Comment by Mishiranu** [comment]
Threads watcher downloads a number of posts without any content, so it's not possible.

**Comment by GiRaFa-SM** [comment]
Sorry for mentioning other chan app here, but can you explain how Clover do that?

**Comment by Mishiranu** [comment]
Clover analyses posts and looks for links to your posts, so Clover always needed to read and analyze a whole thread.

**Comment by ololoe** [comment]
So can't you make an option to refresh a thread including posts, at least for sosach?

**Comment by Outlander0** [comment]
I wouldn't mind this even with its flaws

**Comment by atriede** [comment]
I think this would be great. A notification system for new posts would also be good, especially for slow boards/threads.

**Comment by Zero3K** [comment]
I also would like to see this feature added to it.

**Comment by ololoe** [comment]
> Threads watcher downloads a number of posts without any content, so it's not possible.

It is possible to download new posts after you see it's been updated.

**Comment by Mishiranu** [comment]
Notifications are implemented in 3.1.0.
