### ISSUE TITLE
Thumbnails don't load in local host (and suggestions related to local host) 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#41]
In the previous version thumbnails was loading without problems, but now they aren't loading. I tried everything except cleaning app data (I have many favorites saved and I don't want lost) 

You remember the suggestion about archiving threads with their original names? Since this isn't possible I have other idea, and at same time  a question. 

When you save an image and the dialog prompt ask to save file and choose the location, the app asks to save with their original names and detailed names, in this process what your app do? 

It renames the original filename (according to server name with details/or original filenames? 
If any of my thoughts are correct.. 
My request is, in local host, when you save files in the localhost gallery or individually, the app rename the file to their original filenames or detailed (user choice) using the same method above.

And other request, is it possible to make a custom directory setting when saving files in local host (in the folder called localhost/null and the threads) like I requested In the past. 

Thank you so much.

**Comment by Mishiranu** [comment]
> I have many favorites saved and I don't want lost

You can make a backup in settings.

I don't know, I've checked it and it seem that it works. How about images? Are they open?
And how they not loading? Do you see a warning icon over thumbnails?

> Since this isn't possible I have other idea, and at same time a question. 

When I told about problems with it, I meant about what you told. There are no problems with saving, but technically it's wrong (all server names will be deleted even in localhost extension) and can cause some problems with repeating file names (some files can have the same original file name).

> And other request, is it possible to make a custom directory setting when saving files in local host (in the folder called localhost/null and the threads) like I requested In the past. 

The problem is that localhost extension can't find all your directories where you saved your threads. So this path is hardcoded.

**Comment by GiRaFa-SM** [comment]
I see a black Thumbnail, as if the thumbnail file was deleted /or doesn't saved when archiving the thread.  (cleaning data worked) thanks for the tip. 

I meant about "saving files" in local host extension, in this process the app duplicate files in the folder localhost/null and their respective folders, in this process, the file is saved with his server name, my request was/is, rename the file with the original name (you said the original name is saved /added on HTML settings) I wanted to know if is possible, in this process the app rename those files (on localhost/null) with their original names.
Sorry, I think my communicative ability is low or something, I need 2 steps to explain something simple, who knows.. Lol
No problem, most threads I save are of /a/ and some others are from /g/. 
 Regards

**Comment by Mishiranu** [comment]
You mean downloading files from localhost extension? If you enable saving with original file name, it will save with original file name...
Or not. I just noticed that it doesn't work in localhost. It's bug, I'll think about how to fix it.

**Comment by Mishiranu** [comment]
Ok, I fixed it.

**Comment by GiRaFa-SM** [comment]
It's already enabled and it's not saving with the original name in localhost extension. It's up on git? Thank you so much.

**Comment by GiRaFa-SM** [comment]
I think i found the reason why thumbnails doesn't load on localhost. 

There's two reasons.. 

Seems when you load the thread, the appeal create an "thumbnail cache" and when you archive, the thread is already cached in your device. 

Sometimes I clean app cache (when it's around 120mb) and when I go to localhost I can't see the thumbnails, because they are blacked out. 

If i clean app data (using default Android app Settings) saving before saving personal settings, and after restoring personal settings, the app is able to work normally again. But at some time when i come back to localhost, the same thing happens again. 

We can do two things. 

Clean app cache (using Android settings app) 
Or go to a archived thread of your choice, clicking in gallery and press back, you'll be able to see the thumbnails from your archived threads. 

Sorry for the long text, and I have another request (next post)

**Comment by GiRaFa-SM** [comment]
It's possible "save" localhost files with their original date/time?

**Comment by Mishiranu** [comment]
I still can't reproduce your bug. After clearing cache, I can see thumbnails in localhost.

App's has different thumbnail caches for different imageboards, so this can't be true.

> It's possible "save" localhost files with their original date/time? 

No. You can copy them manually from archive folder, but dashchan doesn't work so. It "downloads" all images to cache directory first for every imageboard (and it even thinks localhost is remote site too) and then copies this file, so dates are differ. I need to make a serious changes to extensions API to allow what you want, but I won't.

**Comment by GiRaFa-SM** [comment]
May I print my bug? There's a chance of this be a bug because I'm using external storage to store files?

**Comment by Mishiranu** [comment]
Sorry, I forgot about you.

How do you want to print it?

I don't know, but if Dashchan have permission to read from external storage, it should read properly.
