### ISSUE TITLE
Small typo in settings-info (Portuguese) 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#44]
I'm Brazilian, and the word "licensa " doesn't exist. 
Please fix it writing "licença" 

The two texts are currently written 
"licensas open source"
"detalhes da licensa open source" change licensa to licença

**Comment by Mishiranu** [comment]
Lol, even IDE warned me about this typo, but I'm not the one who made translation, so I was afraid to correct it.
I'll fix it in next update.

**Comment by GiRaFa-SM** [comment]
Please don't close this issue at least I find more grammar errors. I'm sure I've seen more.

**Comment by GiRaFa-SM** [comment]
Can you please send me the xml file with the Portuguese translation? I'll fix some strings.

**Comment by Mishiranu** [comment]
Here you go.

[strings.txt](https://github.com/Mishiranu/Dashchan/files/172816/strings.txt)

It was edited a little since last update (not by me ofc).

**Comment by GiRaFa-SM** [comment]
https://drive.google.com/file/d/0B1VV-pX3WjWLdlh2UUJJTHI2SE0/view?usp=docslist_api

Here you go. 
This translation is good(current translation) , has some grammar errors but is very understandable. I edited it with more formal texting and corrected this errors, also, some sentences can be changed to smaller sentences, so I changed it.

**Comment by Mishiranu** [comment]
> Usuário banido , visite 4chan.org/banned para mais informações

You needn't to provide this information. Also Dashchan isn't only 4chan client, lol. So I'll leave "Usuário banido" only.

I'll replace your translation, ofc. I must think about using translation system where anybody can make a translation... It's not easy to sync your translations.

**Comment by Mishiranu** [comment]
> Notificar ao ao fim do download
> ao ao

It's a typo?

**Comment by GiRaFa-SM** [comment]
I thought it will be better include this information, because I was banned twice on 4chan, and the first time I didn't know how I could solve this situation. 

Sorry for that. This is a typo, edit this to "notificar ao fim do download" (I was editing the xml file using my phone, probably SwiftKey error when I was typing(double words). Sorry again.

**Comment by Mishiranu** [comment]
> <string name="message_file_exists">Repeated files are prohibited</string>

I think it's wrong to translate it as "Arquivo(s) já existe(m)", especially given the fact that there may be several files and brackets look awful here.

> <string name="text_sage_description_infinitive">Não levantar o thread</string>

Make it shorter (like "Don't bring up" in english). It's a description near sage checkbox on posting.

**Comment by GiRaFa-SM** [comment]
But in my language it represents 1 or more files, so in Portuguese this fits better. And in this way this isn't is misinterpreted in my language. 

If you want, you can change to "arquivos já existem ". No problem. 

"repeated files are prohibited" 
Here I can't find this sentence in xml file, anyway, if it isn't translated, you can change to: "Arquivos repetidos são proibidos"

" the previous text was "não abra"  and literally means "don't open" dont open what? 

Don't bring up means "bump" the thread isn't it? 

You can change the text for "Não levantar o fio".

**Comment by Mishiranu** [comment]
>  Here I can't find this sentence in xml file, anyway, if it isn't translated, you can change to: "Arquivos repetidos são proibidos"

This is what must be instead of "arquivos já existem". I'll replace it.

> You can change the text for "Não levantar o fio". 

"Não levantar" will be the best option, but I don't sure it's correct.

**Comment by GiRaFa-SM** [comment]
Onde I saw this same text when I posted a file with the same name on 4chan threads(the sentence "repeated files are prohibited") so I thought that sentence would be shown in this situation.

Once you update your app, I'll check this and give you a reply about it. 

You can change the text" não levantar o fio" to "não levantar" I just think it would be confusing for someone who is using this app for the first time.

**Comment by GiRaFa-SM** [comment]
App was updated today (22-3) and applied the new translation, so I'm closing this issue.
