### ISSUE TITLE
WebM are not opening

### ISSUE THREAD

**Issue by JamesJGoodwin** [Mishiranu/Dashchan#47]
Hi. I've installed WebM extension for Dashchan, but i still can't watch webms. Application says "Неизвестный адрес" (Unknown address). Is it a bug? And how can i fix it?
![screenshot_2016-04-25-14-17-54](https://cloud.githubusercontent.com/assets/17240507/14782303/39a935ea-0af1-11e6-916d-f45cca3712d4.png)

**Comment by Mishiranu** [comment]
Просто установить модуль недостаточно, надо ещё в настройках включить сам плеер (Настройки — Содержимое — Использовать встроенный видеоплеер).

**Comment by JamesJGoodwin** [comment]
Было бы здорово, если бы после установки модуля WebM эта галочка ставилась автоматически. Спасибо.
