### ISSUE TITLE
Support for Endchan

### ISSUE THREAD

**Issue by Kiyuubi** [Mishiranu/Dashchan#48]
Could it be possible to add support for Endchan?  Here is the domain: https://endchan.xyz/

Thanks.

**Comment by Mishiranu** [comment]
I think it possible but only after I release a new version of client. This imageboard is very unusual.

**Comment by Kiyuubi** [comment]
Thanks friend.

**Comment by odilitime** [comment]
We have a 4chan compatible api on port 9090

**Comment by Mishiranu** [comment]
API is not a problem, but posting is not possible to implement until next version of Dashchan.
Endchan has a good API, but there are 2 lacks: I don't know number of thread replies in board page and I don't know a default name on board. I've always reported about them in operate thread before.

**Comment by Mishiranu** [comment]
It seems that deleting is broken. I can't delete my posts, but can delete my images. I receive success message, even trying to delete foreign post, but site tells me post deleted. Post remains in place ofc. It's a bug?

**Comment by Mishiranu** [comment]
Finally it's ready.
https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanEndchan.apk

**Comment by odilitime** [comment]
Thanks working on the data you need too. The post deletion may just be lynxchan's normal delay. The delete goes through but the HTML takes a bit to update.

**Comment by Mishiranu** [comment]
Yes, you are right, it's just a long delay.
But I still can delete foreign posts. I receive a success message, but I must show user that password incorrect in this case.
