### ISSUE TITLE
Webm

### ISSUE THREAD

**Issue by Serpent379** [Mishiranu/Dashchan#49]
При открытии вебм,на очень малое время включается звук и выключается,получается писк и похоже что на всю громкость
Zenfone 2 551ml 5.0

**Comment by Mishiranu** [comment]
Это происходит при полностью выключенном звуке? Мне уже сообщал кто-то об этом, но я как-то не представляю, как такое возможно. Громкостью управляет система, и если я воспроизвожу звук при выключенном в системе звуке, его быть не должно совсем.
После следующего обновления можно попробовать поставить пару экспериментов, но я очень сомневаюсь, что это удастся исправить.

**Comment by ivan-nekochan** [comment]
Тоже такое есть, при всём выключенном, если листать вебмки, то включается на миллисекунду звук, и выключается. Возможно, из-за кодеков, кстати.

Xiaomi 1SW AOSPB 6.0.1

**Comment by Mishiranu** [comment]
Всегда такое происходит?

**Comment by ivan-nekochan** [comment]
Ну где-то через 5 вебмок. Походу, звук не успевает на ноль падать, или что-то ещё. В общем, я включаю вебмку, и листаю их, а они в это время сами и включаются, и бывает что сами начинают играть. И да, зачем такие частые обновления? Можно же просто выпускать пореже, но дошлифовать получше, а то прям чуть ли не каждый день.

**Comment by Mishiranu** [comment]
Звук достаточно громкий? Если громкость не на 0 поставить, а на минимум перед нулём, когда звук еле слышен, то тоже слышно?

Последнее крупное обновление вышло полтора месяца назад, а промежуточное — 3 недели назад. Разве это часто?

**Comment by Mishiranu** [comment]
Получилось воспроизвести этот баг на одном видео. Очень странно, такое ощущение, будто первые миллисекунды воспроизводятся на максимальной громкости независимо от её настройки. Сделал костылик, чтобы первые 40 миллисекунд аудио не звучало, и это сработало. Думаю, так и оставлю.
