### ISSUE TITLE
Theme not applied when starting up

### ISSUE THREAD

**Issue by soupman2001** [Mishiranu/Dashchan#5]
http://i.imgur.com/3FC5SWk.png

http://i.imgur.com/Jjqz5GZ.png

**Comment by Mishiranu** [comment]
When applications starts, it shows a stub window with default app theme. This theme can't be changed depending on the settings.

**Comment by soupman2001** [comment]
Have you considered using a splash screen instead of a stub window?

**Comment by Mishiranu** [comment]
No, I don't like splash screens.
But I'll make stub window more neutral. In next version there will be white window without action bar, so a transition effect won't be so evident.
![device-2015-08-17-225941](https://cloud.githubusercontent.com/assets/8524113/9313394/716b399c-452b-11e5-9fc4-3693c1ae8412.png)

**Comment by soupman2001** [comment]
Why hide the action bar, I don't know of any other app that does this.

**Comment by Mishiranu** [comment]
> I don't know of any other app that does this.
All jewgle apps do.

**Comment by soupman2001** [comment]
I'm sorry I was thinking of the navigation bar, which isn't visible in your screenshot I assume because you have physical/capacitive buttons.
