### ISSUE TITLE
Webm player shows unknown address

### ISSUE THREAD

**Issue by kgibson9489** [Mishiranu/Dashchan#51]
After updating to the latest dashchan webm plugin, attempting to play a webm shows an error: "unknown address".

**Comment by Mishiranu** [comment]
Try to install test version. Open updating window, click on Dashchan, choose "Test" and install it. Does this solve a problem?

What device do you have?

**Comment by kgibson9489** [comment]
Test version still shows the same error. I am running on an LG V10 (T-Mobile, USA), stock rom.

**Comment by Mishiranu** [comment]
Can you make a log like it told [here](https://github.com/Mishiranu/Dashchan/wiki/Home-EN#the-app-shows-extension-error-or-unable-to-download-data-messages) (in the bottom)?
