### ISSUE TITLE
Crash while updating

### ISSUE THREAD

**Issue by podabed** [Mishiranu/Dashchan#52]
What do you need for fix this? Logs, screens etc.

**Comment by Mishiranu** [comment]
All crashes are stored in "errors" dir, read [here](https://github.com/Mishiranu/Dashchan/wiki/Home-EN) in the bottom. Just open this dir and attach last logs.

**Comment by podabed** [comment]
[error-1443745719808.txt](https://github.com/Mishiranu/Dashchan/files/303777/error-1443745719808.txt)
[error-1451611672105.txt](https://github.com/Mishiranu/Dashchan/files/303778/error-1451611672105.txt)
[error-1451611678348.txt](https://github.com/Mishiranu/Dashchan/files/303779/error-1451611678348.txt)
[error-1451611686626.txt](https://github.com/Mishiranu/Dashchan/files/303780/error-1451611686626.txt)
[error-1453795787759.txt](https://github.com/Mishiranu/Dashchan/files/303781/error-1453795787759.txt)
[error-1453795794659.txt](https://github.com/Mishiranu/Dashchan/files/303782/error-1453795794659.txt)
[error-1453795802055.txt](https://github.com/Mishiranu/Dashchan/files/303783/error-1453795802055.txt)
[error-1453795818938.txt](https://github.com/Mishiranu/Dashchan/files/303784/error-1453795818938.txt)
[error-1455021744233.txt](https://github.com/Mishiranu/Dashchan/files/303785/error-1455021744233.txt)
[error-1455021753870.txt](https://github.com/Mishiranu/Dashchan/files/303788/error-1455021753870.txt)
[error-1455506375671.txt](https://github.com/Mishiranu/Dashchan/files/303786/error-1455506375671.txt)
[error-1455506425921.txt](https://github.com/Mishiranu/Dashchan/files/303787/error-1455506425921.txt)
[error-1455506472982.txt](https://github.com/Mishiranu/Dashchan/files/303789/error-1455506472982.txt)
[error-1455554560423.txt](https://github.com/Mishiranu/Dashchan/files/303790/error-1455554560423.txt)
[error-1456928717918.txt](https://github.com/Mishiranu/Dashchan/files/303791/error-1456928717918.txt)
[error-1458671800714.txt](https://github.com/Mishiranu/Dashchan/files/303792/error-1458671800714.txt)
[error-1458741429297.txt](https://github.com/Mishiranu/Dashchan/files/303793/error-1458741429297.txt)
[error-1459269827337.txt](https://github.com/Mishiranu/Dashchan/files/303794/error-1459269827337.txt)
[error-1459306523096.txt](https://github.com/Mishiranu/Dashchan/files/303800/error-1459306523096.txt)
[error-1460261071211.txt](https://github.com/Mishiranu/Dashchan/files/303795/error-1460261071211.txt)
[error-1460990909949.txt](https://github.com/Mishiranu/Dashchan/files/303796/error-1460990909949.txt)
[error-1464459072038.txt](https://github.com/Mishiranu/Dashchan/files/303797/error-1464459072038.txt)
[error-1464497974210.txt](https://github.com/Mishiranu/Dashchan/files/303799/error-1464497974210.txt)
[error-1464497997170.txt](https://github.com/Mishiranu/Dashchan/files/303798/error-1464497997170.txt)
[error-1464498032576.txt](https://github.com/Mishiranu/Dashchan/files/303801/error-1464498032576.txt)
[error-1464525556968.txt](https://github.com/Mishiranu/Dashchan/files/303802/error-1464525556968.txt)
[error-1465122267515.txt](https://github.com/Mishiranu/Dashchan/files/303803/error-1465122267515.txt)
[error-1465315356940.txt](https://github.com/Mishiranu/Dashchan/files/303804/error-1465315356940.txt)

**Comment by Mishiranu** [comment]
It seems like your download manager is disabled or you even don't have it. Dashchan uses system download manager to download updates.
http://stackoverflow.com/questions/21551538/how-to-enable-android-download-manager

**Comment by podabed** [comment]
![screenshot_20160608-080517](https://cloud.githubusercontent.com/assets/4352168/15879762/770ed004-2d59-11e6-9c19-ac0be5d60dfb.png)

**Comment by Mishiranu** [comment]
No, it's an UI app. Can you find the Download Manager?

**Comment by Mishiranu** [comment]
You can try to enter this in terminal emulator:
```
pm hide com.android.providers.downloads
pm unhide com.android.providers.downloads
```
At least I was able to reproduce the same problem using the first line.

**Comment by podabed** [comment]
![tmp_6663-screenshot_20160608-0852011612897810](https://cloud.githubusercontent.com/assets/4352168/15880364/203643d8-2d5f-11e6-9955-0afd81543e50.png)

**Comment by Mishiranu** [comment]
Try to disable and enable it again, lol.

**Comment by podabed** [comment]
So, everything's alright. I greenifyed the Download Manager. That's the reason of the "bug". Sorry for my stupidity. Please, close this issue.
