### ISSUE TITLE
Api keys in repo

### ISSUE THREAD

**Issue by metjka** [Mishiranu/Dashchan#53]
https://github.com/Mishiranu/Dashchan/blob/master/src/com/mishiranu/dashchan/C.java#L57

**Comment by Mishiranu** [comment]
А это очень плохо? Их в любом случае можно было бы достать из байткода.

**Comment by Mishiranu** [comment]
Впрочем, ладно. Вынес ключи во внешний файл, они автоматически будут подцепляться при сборке градлом из `private.properties`.

**Comment by metjka** [comment]
Ну не знаю. Мне кажется, плохой тон добавлять ключи в реп.

niedz., 12 cze 2016, 18:15 użytkownik Fukurou <notifications@github.com>
napisał:
