### ISSUE TITLE
Support for cable6.net

### ISSUE THREAD

**Issue by eti1337** [Mishiranu/Dashchan#54]
Hey,
So I was wondering if you could add support for [cable6.net](https://cable6.net/), would it be possible ?
It's french imageboard that I often go on, if you have any problem translating anything you can always ask me.

Thanks

###### And also, your app is fantastic.

**Comment by Mishiranu** [comment]
I think it would. I'll try to make it later.

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanCableSix.apk

**Comment by eti1337** [comment]
Awesome ! Thanks a lot

**Comment by eti1337** [comment]
Uh oh.
Why is this happening ?
![screenshot 18 jun 2016 19-43-38](https://cloud.githubusercontent.com/assets/14180792/16172670/44e3754e-358d-11e6-9f0d-96902687ff1a.png)

**Comment by Mishiranu** [comment]
I don't know, I'm seeing this error even in regular browser on my phone. Just disable HTTPS in extension settings (not in general settings) and it will work excepting connection won't be secure.

**Comment by eti1337** [comment]
Yeah, it works now.
Thanks again
