### ISSUE TITLE
Ronery.me support

### ISSUE THREAD

**Issue by kisleey** [Mishiranu/Dashchan#55]
Здравствуйте.
Хочу, чтобы вы добавили модуль для имиджборды [ronery.me](https://ronery.me/).
Заранее спасибо.

**Comment by Mishiranu** [comment]
Его роскомпозор блокирует что ли?
Сделать можно попробовать, хотя движок достаточно странный.

**Comment by Mishiranu** [comment]
У вас есть favicon в большем разрешении?

**Comment by kisleey** [comment]
Не имеется.

**Comment by Mishiranu** [comment]
Ладно, тогда немного странный вопрос — что нарисовано на этом фавиконе? Не могу никак разглядеть, а ведь мне его векторизовать нужно будет

**Comment by kisleey** [comment]
Шар светло-зелёного цвета в шапке-ушанке и лыжных очках.

**Comment by Mishiranu** [comment]
Лол, а я подумал, что это печатная плата с разъёмами.

**Comment by Mishiranu** [comment]
Готово.
https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanRonery.apk
