### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wakaber** [Mishiranu/Dashchan#56]
Мб перманентные неймы лучше вернуть? Только сделать их board-specific, бо не очень удобно трип по несколько раз вводить (я довольно часто между аппами переключаюсь, и клиент вылетает из памяти)

Еще было бы гуд добавить интерфейс для скачивания расширений из самого приложения (переписать апдейтер?)

**Comment by Mishiranu** [comment]
В приложении сейчас есть "черновики тредов" (до 15 штук, хранятся по принципу LRU), в которых хранятся некоторые настройки в пределах одного треда (а именно имя, емаил, пароль, сажа, галка опа и иконка). Делать настройку конкретно для имени по умолчанию мне не хотелось бы, но могу количество черновиков увеличить, если 15 мало.

Со скачиванием другая история. Путь для загрузки и обновления расширения прописывается в самом расширении, а не в клиенте, что позволяет кому угодно создавать расширения и клиент будет его обновлять.
К тому же так получилось, что изначально приложение создавалось исключительно для 2ch.hk, там же находится тред поддержки приложения. Администрации сайта такой подход не понравится, но это уже совсем другая история.

**Comment by wakaber** [comment]
Думаю 15 хватит.

Okay then.
