### ISSUE TITLE
Rotate images according to exif tag orientation before uploading.

### ISSUE THREAD

**Issue by ferongr** [Mishiranu/Dashchan#57]
Taking an image in portrait mode and then posting it results in the images shown up rotated in the thread. It would be nice if Dashchan rotated the image before uploading it.

**Comment by Mishiranu** [comment]
I think I can try to do it but only optional. Image rotation means its re-encoding which leads to increasing a size.

**Comment by Mishiranu** [comment]
In next version there will be a warning when you attach an image if image contains exif with orientation data. In this case you can click on image and choose "Re-encode image" option.

**Comment by ferongr** [comment]
Excellent! Does the encoder use the same encoding parameters as the
encoding image?

**Comment by Mishiranu** [comment]
No, and it's a problem. Jpeg doesn't store information about it's quality so I re-encode with 100% quality. There are some methods allowing to guess the quality but they are not simple.

**Comment by Mishiranu** [comment]
It's done.
