### ISSUE TITLE
1chan.ca support

### ISSUE THREAD

**Issue by kisleey** [Mishiranu/Dashchan#59]
Здравствуйте.
Было бы неплохо, если бы Вы создали расширение для последнего живого колчана.
Спасибо.

**Comment by Mishiranu** [comment]
Это ведь новостной сайт, да? Ты хочешь, чтобы каждая новость была представлена в виде отдельного треда, а комментарии к ними были постами? Всё таки это далеко не имиджборд.

**Comment by kisleey** [comment]
Именно. Это новостной сайт, но анонимный и частично выполняющий функцию имиджборда.

**Comment by Mishiranu** [comment]
Ладно, попробую потом.

**Comment by Mishiranu** [comment]
Готово.

Для того, чтобы приложить ссылку к новости, её следует оставить в 1 строке сообщения.

**Comment by kisleey** [comment]
Просьба сделать ещё два дополнения.
Первое - на колчане есть скрытые смайлики, вставляемые кодом `:smilename:`, их список - чуть ниже. Прошу сделать так, чтобы в тех местах, где они стоят, отображался их код, а то не всегда понятно, что имел ввиду собеседник, когда они не отображаются.
[:nyan:](https://1chan.ca/img/nyan.gif) [:coolface:](https://1chan.ca/img/coolface.gif) [: trollface:](https://1chan.ca/img/trollface.gif) [: rage:](https://1chan.ca/img/rage.png) [:sobak:](https://1chan.ca/img/sobak.gif) [:awesome:](https://1chan.ca/img/awesome.png) [:ffuu:](https://1chan.ca/img/ffuu.png) [:okay:](https://1chan.ca/img/okay.png) [:desu:](https://1chan.ca/img/desu.gif) [:pauk:](https://1chan.ca/img/pauk.gif) [:popka:](https://1chan.ca/img/popka.gif) [:popka2:](https://1chan.ca/img/popka2.gif) [:doge:](https://1chan.ca/img/doge.png) [:sheez:](https://1chan.ca/img/sheez.png) [:slon:](https://1chan.ca/img/slon.gif) [:spice:](https://1chan.ca/img/spice.png) [:cheez:](https://1chan.ca/img/cheez.gif) [:weed:](https://1chan.ca/img/weed.gif) [:hero:](https://1chan.ca/img/hero.png) [:makak:](https://1chan.ca/img/makak.gif) [:yajka:](https://1chan.ca/img/yajka.png)

Второе - имеется озвучивание текстов #%вот этим вот тегом %#. При озвучивании вставляется аудиозапись TTS яндекса, формат вставки чуть ниже. Тоже надо сделать так, чтобы озвучиваемый текст отображался.
`<audio controls="" src="https://tts.voicetech.yandex.net/tts?text=озвучиваемый текст&amp;lang=ru_RU&amp;format=mp3&amp;quality=hi&amp;platform=web&amp;application=translate&amp;chunked=0&amp;mock-ranges=1"></audio>`

**Comment by Mishiranu** [comment]
Про смайлики я знаю и, что интересно, я их реализовывал, чтобы они именно кодом отображались. Странно, что сейчас это не работает.

Озвучивание постараюсь сделать.

**Comment by kisleey** [comment]
Да, с отображением смайликов всё нормально. Я, видимо, немного запутался.
Пост с озвучиванием оставил [здесь](https://1chan.ca/alone/res/100/#102), в дашчане отображается пустой пост.
И пока не забыл: если копировать из /news/all/ ссылку на новость, то получается ссылка вида 
[https://1chan.ca**/news/all/**res/227272/](https://1chan.ca/news/all/res/227272/), которая не работает, так как все новости (включая не одобренные и скрытые) распологаются в /news/res/*, следовательно, правильная ссылка должна быть вида [https://1chan.ca**/news/**res/227272/](https://1chan.ca/news/res/227272/). Прошу это тоже пофиксить.

**Comment by Mishiranu** [comment]
Сделал, ссылки тоже должны правильно работать. Модуль обновил.

**Comment by kisleey** [comment]
Всё-таки смайлики не все работают. 
[Здесь](https://1chan.ca/alone/res/100/#125), я создал пост со смайликом :sheez:. В дашчане он пуст. 
Учитывая тот факт, что рано или поздно будут добавлены новые смайлики, лучше будет сделать парсер, который будет искать в теле поста/коммента код вида `<img src="https://1chan.ca/img/aaaaaa.bbb" alt="" width="XX" height="YY">` и выводить его в виде `:aaaaaa:` (по традиции название изображения смайлика такое же, как у его кода), дабы постоянно не обновлять модуль при нахождении нерабочих смайликов.

**Comment by kisleey** [comment]
Догадался глянуть в исходник парсера. Оказывается, это уже есть. А вы просто прописали в коде парсить смайлики в формате GIF, забыв про смайлики в PNG. Прошу починить.

**Comment by Mishiranu** [comment]
Исправлено.

**Comment by kisleey** [comment]
Там прикрутили новую капчу, схожую с апачановской.
Не помешало бы обновление, добавляющее её поддержку.

Есть пара нюансов:
Из-за криворукости какалика для создания новостей требуется ввести аж две капчи: цифровую и выбор нужного предмета/персонажа. Неправильно введённая цифровая капча приводит к появлению фразы "Капча введена неверно" на странице ввода текста новости, а неправильно выбранный персонаж приводит к обновлению страницы с добавленным ?weedcaptcha_error в URL.

**Comment by Mishiranu** [comment]
При добавлении комментария, кажется, тоже требует 2 капчи вводить.

Не нахожу чекбокс. VIP только вижу, это оно?

**Comment by kisleey** [comment]
>VIP только вижу, это оно?
Да.

**Comment by mintplague** [comment]
А ещё там есть поддержка [пссскодов](https://1chan.ca/pssscode), отключающих все виды капчи (для того, чтобы он отобразился после ввода на той странице, нужно её обновить).

Введённый пссскод сохраняется плейнтекстом в куке "pssscode", и при открытии страниц с ней вся капча вырезается и посты проходят без неё.

Хорошо было бы иметь и их поддержку. Свой псскод я вам отправил электронной почтой, дабы вы могли проверить их работоспособность.

**Comment by Mishiranu** [comment]
Обновлено.

**Comment by mintplague** [comment]
А отображение скорости постинга можно? На сайте она появляется, если навести мышь на жёлтую белку у логотипа.

**Comment by Mishiranu** [comment]
Вообще скорость доски отображается для конкретной доски, а не для всех целиком. Можно сделать такое отображение только в "news-all", пожалуй.

**Comment by mintplague** [comment]
>Можно сделать такое отображение только в "news-all", пожалуй.

Да, можно.
