### ISSUE TITLE
Search through OP content

### ISSUE THREAD

**Issue by soupman2001** [Mishiranu/Dashchan#6]
Maybe add a setting that would toggle between searching all posts on a board and only the opening posts of threads on a board. Much like the average catalog search function works on imageboards.

**Comment by Mishiranu** [comment]
If imageboard doesn't support searching, but supports catalog, client performs searching in catalog (on 4chan, for example). 4chan API provides catalog of threads with last replies, so I show replies in result if they matches search request too.

**Comment by Mishiranu** [comment]
Now the "search" option also includes filtering threads list. You can go to catalog and then filter a list of threads.
