### ISSUE TITLE
Translations (PT-BR) 2.8.0 version

### ISSUE THREAD

**Issue by GiRaFa-SM** [Mishiranu/Dashchan#60]
Highlight unread posts 
Destacar posts não-lidos 

Hide eventually 
Esconder eventualmente 

Hide on tap 
Esconder ao tocar 

Never highlight 
Nunca destacar 

Sorry for opening an issue just for this.

**Comment by Mishiranu** [comment]
Ok, I've added it.

You can also check the difference between these files:
https://github.com/Mishiranu/Dashchan/blob/master/res/values/strings.xml
https://github.com/Mishiranu/Dashchan/blob/master/res/values-pt-rBR/strings.xml

May be you'll find something more to translate.

**Comment by GiRaFa-SM** [comment]
I'll give a look into when possible, I'm away from my PC now.
