### ISSUE TITLE
Standalone Video Player for looping local videos

### ISSUE THREAD

**Issue by keiex** [Mishiranu/Dashchan#62]
It's a silly request, but could you make the video player a standalone app? no interface, just so it can use open with from gallery apps to loop local files seamless,

Thanks

**Comment by GiRaFa-SM** [comment]
QuickPic and MXPlayer are able to play WebM videos. Also, QuickPic Is a very good software for pretty much everything related to media files. In MXPlayer you can choose loop options in settings. 

To be honest I didn't understand very well what you asked/said (English isn't my first language) , but if you want an WebM player in app there is an plugin available in Mishiranu's github.

**Comment by keiex** [comment]
No i want an apk with only the video player so it can open webms/videos.

Example: I click the webm from the gallery and it asks me to open with the video player and them loops/repeat the video.

QuickPic 4.5.2 doesn't loop videos and Mx Player lags at the end.

Mishiranu implementation of the webm player is very good and loops videos very well with no lag at the end.

**Comment by Mishiranu** [comment]
I think it's a bad idea. In my opinion my video player isn't good. It's slower than system player or MX and has some bugs. But it supports streaming.

I don't want to do it. But the source code is open, you (or anybody else) can try to do it by himself, it might be not so hard.

**Comment by keiex** [comment]
Thanks for the answer, i thought about asking first to see if you liked. I never made an android app, but I'll try to put it together.
