### ISSUE TITLE
Volume Keys Navigation

### ISSUE THREAD

**Issue by ivantyr** [Mishiranu/Dashchan#64]
Is it possible to implement volume keys actions such as thread scrolling (as PgUp/PgDn style or Next/Previous post) and Next/Previous file in Gallery view?

**Comment by Mishiranu** [comment]
It's possible, but for what purpose? All smartphones has a convenient touch screen that allows you to scroll as you wish.

I don't think it's necessary. This pattern is quite unusual for android applications.
