### ISSUE TITLE
Поддержка TinyIB.

### ISSUE THREAD

**Issue by ozu-kun** [Mishiranu/Dashchan#65]
Сделай модули ozuchan.ru и 0nyan.ml пожалуйста.

**Comment by Mishiranu** [comment]
Модули готовы, но выпустить их я смогу только после следующего обновления клиента.

Озучан почему-то грузиться перестал, все треды пропали.

**Comment by ozu-kun** [comment]
Спасибо.

Бывает, когда страница не грузится или выдает код какой-то ошибки, да, это из-за хостинга. Треды вновь появились, но уже новые.

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanOzuchan.apk
https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanNullnyan.apk

**Comment by ozu-kun** [comment]
Добавь капчу пожалуйста.

**Comment by Mishiranu** [comment]
Добавил.

**Comment by kisleey** [comment]
После очередного шатания тайнибы на нульняне отклеились картинки и заголовки досок. Пофикси, пожалуйста.

**Comment by Mishiranu** [comment]
Обновлено.

**Comment by kisleey** [comment]
Теперь отклеились картинки и дата постов. Прошу пофиксить.

**Comment by Mishiranu** [comment]
Исправлено.

**Comment by kisleey** [comment]
Озучан сдох, переноси в obsolete.

**Comment by kisleey** [comment]
На нульняне появились превью всех постов, получаемые из БД: то бишь, для превью любого поста открытие треда теперь не требуется. Прошу добавить их поддержку в модуль.

Кроме того, если клиентом поддерживается поиск по всей борде (не помню, есть ли такая фича, так как модулей для борд со встроенным поиском среди установленных мною не присутствует), то можно и добавить появившийся поиск (/search.html, есть характерная иконка).

**Comment by Mishiranu** [comment]
Готово.

Передача параметров для запроса постов через заголовки HTTP запроса меня повеселила, конечно.

**Comment by devarped** [comment]
1. Переезд на nullnyan.net;
2. Появление SSL.
Обнови модуль.

**Comment by Mishiranu** [comment]
Обновил
