### ISSUE TITLE
4chan Captcha Problem 

### ISSUE THREAD

**Issue by justinhood1** [Mishiranu/Dashchan#66]
Sometimes when I go to post something on 4chan and I'm trying to do the Captcha I click a picture and it closes and opens up a new window with a new Captcha. You have to close the app and reopen for it to work sometimes.

I'm running Android 6.0 on a Motorola G3

**Comment by Mishiranu** [comment]
Are you sure it's a new captcha? May be it's the same with replaced clicked image? In this case you must choose all required pictures until until they end. Then click the "OK" button.

**Comment by justinhood1** [comment]
I'm an idiot. You're right. Sorry about that.
I love the app by the way

**Comment by explouad** [comment]
im getting the same thing. I tap anywhere on the captcha pop-up, it fades out, then opens another pop-up with another set of images. Galaxy S6 Android 6.0.1

**Comment by Mishiranu** [comment]
Try to switch to recapcthav1 in settings, it's more stable.
