### ISSUE TITLE
alterchan.in support

### ISSUE THREAD

**Issue by kisleey** [Mishiranu/Dashchan#67]
Здравствуйте.
Мне бы хотелось, чтобы вы сделали модуль для [альтерчана](http://alterchan.in/).
Заранее спасибо за это.

**Comment by Mishiranu** [comment]
Я так понимаю, на сайте нет досок, только теги? Причём одному треду может быть присвоено несколько тегов, так?

**Comment by kisleey** [comment]
Верно.

**Comment by Mishiranu** [comment]
> Нажатием кнопки X пост помещается в черный список, либо УДАЛЯЕТСЯ если этот пост ваш.

То есть свои посты можно удалять? А где эта кнопка находится?

**Comment by kisleey** [comment]
Для того, чтобы эта кнопка отобразилась, надо [ввести пароль](http://alterchan.net/signin.php). Тогда эта кнопка появится у всех постов.

**Comment by Mishiranu** [comment]
Готово https://github.com/Mishiranu/Dashchan/raw/master/update/package/DashchanAlterchan.apk
