### ISSUE TITLE
webm playback jerks

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#68]
When playing Webms, the video and sound jerks and stutters. I'm on a Nexus 6P.

**Comment by Mishiranu** [comment]
It's a known issue, I can't do anything with it. The problem appeared after updating FFmpeg to 3.1.1.
Next version I'll try to rollback to older FFmpeg version (3.0.2), it works faster.

**Comment by libeclipse** [comment]
Also I've noticed that the jerking causes the video to not replay when it reaches the end.
