### ISSUE TITLE
404 для капчи (2ch)

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#69]
Вместо капчи показывается 404, соответственно, отправка не работает.

**Comment by Mishiranu** [comment]
Версия клиента какая?

**Comment by ololoe** [comment]
Свежая, сегодня обновлялся. У тебя воспроизводится?

Кстати, с каких пор появилась капча, раньше же без нее было? Это на всех досках?

**Comment by Mishiranu** [comment]
Нет, не воспроизводится.

Проверь точно, что клиент и модуль последней версии: открой проверку обновлений и обнови всё, что тебе предложит.

Капча уже давно, месяца два как есть. Наверное на всех досках, точно не знаю.

**Comment by ololoe** [comment]
А можно где-то посмотреть установленную версию всей хрени? У меня только написано "версия сборки 2.5.5 (13.03.2016)", это плохо?

**Comment by Mishiranu** [comment]
Настройки — О программе — Проверить наличие обновлений.
Там же можно сразу всё скачать и обновить.
2.5.5 это старая версия, сейчас актуальна 2.8.2

**Comment by ololoe** [comment]
И что это значит? Что у меня обновления не работают? Что теперь делать?

**Comment by Mishiranu** [comment]
Что "это"? Открой

> Настройки — О программе — Проверить наличие обновлений.

и скачай обновления.

**Comment by ololoe** [comment]
Я ж в https://github.com/Mishiranu/Dashchan/issues/69#issuecomment-240504733 написал - обновился, а прога версии от 13.03.2016

**Comment by Mishiranu** [comment]
Ну, так бы и сказал, что через это меню обновлялся.
У тебя случайно не андроид 4.0?

**Comment by ololoe** [comment]
Я и через это меню обновлялся, и через уведомления, и думал что от этих обновлений какой-то смысл будет (автоматом их запилить нельзя будет?).

Ок, и как теперь обновить прогу, не потеряв настройки?

Fire OS базирующееся на андроиде 5.

**Comment by Mishiranu** [comment]
Открой это меню и сделай скриншот. Подозреваю, что ты что-то делаешь не так.
Что значит автоматом?

Обновление не трёт настройки, если ты не удаляешь приложение перед установкой обновления.

Тогда всё должно работать, ты что-то делаешь не так.

**Comment by ololoe** [comment]
После обновления заработало. Но все-таки. Как это сраное обновление работает?

**Comment by Mishiranu** [comment]
Открываешь меню обновлений, нажимаешь на кнопку загрузки, устанавливаешь всё, что скачалось.

Софт не может самостоятельно обновляться на андроиде, это всегда происходит через какой-то установщик, будь то системный установщик или встроенный в гуглплей.

**Comment by ololoe** [comment]
Стоп, что значит устанавливаешь?

Что мешает через какой-то установщик обновляться, тем более у тебя обновления выходят гораздо чаще чем у всего софта что я видел?

**Comment by Mishiranu** [comment]
Нажимаешь на уведомление — открывается установщик, где ты нажимаешь "далее", ждёшь завершения установки, а затем "готово". Вполне нормально.

**Comment by ololoe** [comment]
Еще и на уведомлении щелкать надо было? На всех 4х? Ну нихрена себе, а что же я тогда обновлял? Получается, что почем зря щелкал? Писец, такое говно только пользователи имиджборд могут жрать.

Мало того, что прога чаще всего у меня хочет обновляться, так еще каждый компонент руками обновлять надо? Ну я даже не знаю что на это сказать.

**Comment by Mishiranu** [comment]
> Еще и на уведомлении щелкать надо было? На всех 4х?

Ну да. Открывался бы обычный диалог установки приложения.

> Мало того, что прога чаще всего у меня хочет обновляться, так еще каждый компонент руками обновлять надо? Ну я даже не знаю что на это сказать.

Это происходит не настолько часто, чтобы это как-то напрягало, если у тебя не все модули стоят и ты не обновляешься раз в полгода, конечно.

А иначе никак не получится.

**Comment by ololoe** [comment]
>Это происходит не настолько часто, чтобы это как-то напрягало
Свое г.. не пахнет? :) Никак нельзя сделать как у людей?

**Comment by Mishiranu** [comment]
А как у людей?

**Comment by ololoe** [comment]
Все обновляется само без каких-либо действий со стороны пользователя. И уж точно руками не надо каждый компонент обновлять.

**Comment by Mishiranu** [comment]
Это где так в андроиде сделано, приведи примеры.

**Comment by ololoe** [comment]
Любое приложение, тот же ютуб. Даже если вдруг надо что-то делать руками то это **один** клик и довольно редко.

Блин, это получается, я последние полгода почем зря щелкал? :)

**Comment by Mishiranu** [comment]
> Любое приложение, тот же ютуб.

Неправда, ютуб не обновляется сам. Ютуб обновляет установщик гугл плея. Удали гугл плей — и не будет у тебя ютуб обновляться.

> Блин, это получается, я последние полгода почем зря щелкал? :)

Выходит, что да. Более того, тебе каждый день должно было уведомление об обновлении приходить при запуске дашчана, а ты ничего заподозрил.

**Comment by ololoe** [comment]
Ну так добавь приложение в гугл плей или другой магазин. Почему у других эта проблема решена, а у тебя - нет?

**Comment by Mishiranu** [comment]
В гугл плее уже было, удалили.

Остальные магазины также устанавливают через встроенный установщик. Также будешь мучаться с отдельным обновлением клиента и модулей, ничего это принципиально не изменит.

Тем более мне будет банально напряжно все модули выкладывать.

**Comment by ololoe** [comment]
>В гугл плее уже было, удалили.

Почему?

>Остальные магазины также устанавливают через встроенный установщик. Также будешь мучаться с отдельным обновлением клиента и модулей, ничего это принципиально не изменит.

Чот не понял. Они же сами все обновляют, нет?

>Тем более мне будет банально напряжно все модули выкладывать.

Попробуй это дело автоматизировать.

**Comment by Mishiranu** [comment]
> Почему?

Нашли там "секс и насилие".

> Чот не понял. Они же сами все обновляют, нет?

Нет, тоже вызывая встроенный установщик.

**Comment by Mishiranu** [comment]
https://github.com/Mishiranu/Dashchan/commit/d9beafd1218b38f49c71198adba7acf358aab937 Думаю, с этой штукой должно стать немного удобнее.

**Comment by ololoe** [comment]
Там это где? В самом приложении? 

ЯННП. Другие приложения же обновляются сами по себе, без вмешательства пользователя,нет?

>Думаю, с этой штукой должно стать немного удобнее.

Может, ты еще и расскажешь что эта штука делает? :)

**Comment by Mishiranu** [comment]
> Там это где? В самом приложении?

Ну не на гугл плее же.

> ЯННП. Другие приложения же обновляются сами по себе, без вмешательства пользователя,нет?

Нет, также через встроенный установщик. Исключительное право есть только у гуглплея, потому что это системное приложение.

> Может, ты еще и расскажешь что эта штука делает? :)

Не надо кликать по уведомлениям, сразу запустит установщик. Немного удобнее должно стать.

**Comment by ololoe** [comment]
Баг стоит переименовать.

**Comment by Mishiranu** [comment]
Изначально баг был посвящён ошибке 404, так что пусть остаётся. Лучше бы новую тему создал.
Ну, я в общем-то уже всё сказал насчёт обновления и подробно расписал в треде насчёт альтернативных магазинов.

**Comment by ololoe** [comment]
А сообщения я в новую тему как перенесу?

Тред забудется.
