### ISSUE TITLE
Куда сохраняются настройки?

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#70]
Сделал бекап настроек (о программе - резервное копирование), а куда он сохранился - не видно.

Что за данные внутри? Там полные настройки, включая избранные треды?

**Comment by Mishiranu** [comment]
В папку с загрузками, куда приложение сохраняет все картинки (по умолчанию Downloads/Dashchan внутренней памяти).

Внутри настройки, избранные треды, правила автоскрытия и история.

Кэш тредов не сохраняется.

**Comment by ololoe** [comment]
Ох ё, ты же знаешь сколько там файлов? Там что-то найти нереально, по крайне мере с самого устройства.

**Comment by Mishiranu** [comment]
Ну, отсортируй по дате. К тому же при восстановлении этого самого бэкапа тебе отобразит только список самих бэкапов из папки сохранений, так что нет особо никакой проблемы в этом.

**Comment by ololoe** [comment]
Ну можно было бы и подпапочку создать :)
