### ISSUE TITLE
Установить для постов флаг "мой пост"

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#71]
Хорошо бы если бы была возможность вручную сделать посты "своими", если они написаны с другого устройства, например.

**Comment by ololoe** [comment]
Уже есть.

**Comment by ololoe** [comment]
Можно снять флажок даже с поста, отправленного с устройства. Это точно так надо?

**Comment by Mishiranu** [comment]
Точно надо.

**Comment by ololoe** [comment]
Зачем?

**Comment by Mishiranu** [comment]
Ты очень странно формулируешь вопрос.

Есть флаг "мой пост", его можно установить или убрать. Если тебе интересно, почему можно убирать этот флаг даже у определённых устройством постов — потому что это такой же флаг и на него распространяются те же законы, что и на устанавливаемый пользователем.

Но я подозреваю, что ты не за этим пришёл и ты хочешь предложить более сложную логику, согласно которой установленный приложением флаг снять нельзя. Если это так, то это не нужно.

**Comment by ololoe** [comment]
Можно промахнуться и случайно снять флаг со своего поста, а потом уже не поймешь с какого поста снял. Если приложение точно знает, что пост - твой, то зачем позволять его снимать?

**Comment by Mishiranu** [comment]
Ну, это глупо как-то. Можно промахнуться и очистить все данные на телефоне, например.

Приложение точно не знает, оно часто предполагает, что это твой пост.

**Comment by ololoe** [comment]
Демагогия. Промахнуться легко - зацепил соседний пост.

Речь идет о постах, отправленных из приложения, так что оно должно знать.

**Comment by Mishiranu** [comment]
> Демагогия. Промахнуться легко - зацепил соседний пост.

Тогда вот тебе более реальный пример: помимо "моё сообщение" в меню ещё несколько пунктов. Можно промахнуться по каждому из них.

> Речь идет о постах, отправленных из приложения, так что оно должно знать.

Нет, не должно. Вот отправил ты пост, после этого грузишь тред. Как ты узнаёшь, что конкретный пост именно твой, а не чужой? По содержимому поста. Дашчан это сравнение делает самостоятельно, но это не гарантирует результат. В тех же рулетках много людей пишет "ролл", как ты узнаешь, что конкретный пост именно твой, если ты его отправил, а после обновления в треде появилось ещё 10 постов? Нет никакой гарантии, что твой пост последний. Тут исправление может помочь.

Возможно, ты сейчас ты мне скажешь, что на сосаче тебя скроллит к твоему посту, потому что в адресной строке содерижится номер поста. Действительно, но это исключительная особенность, большинство имиджборд не предоставляет номер отправленного поста и приходится изучать содержимое постов, что не гарантирует правильность.

Я не стану вводить неснимаемый флаг. Даже если закрыть глаза на последние 2 абзаца, в этом нет абсолютно никакой необходимости.

**Comment by ololoe** [comment]
Мой пример тоже абсолютно реальный.

Отлично, значит по крайней мере на сосаче фича реализуема.

**Comment by Mishiranu** [comment]
Смысл моего примера в том, что можно промахнуться и сделать что-то не так не только с этой опцией. Как-то нелепо исправлять в одном месте и не исправлять в другом.

**Comment by ololoe** [comment]
Отметки "мой пост" сохраняются после выхода из программы?

**Comment by Mishiranu** [comment]
Конечно.

**Comment by ololoe** [comment]
> Отметки "мой пост" сохраняются после выхода из программы?

Раньше сохранялись, теперь перестали. Регресс?

**Comment by ololoe** [comment]
Как переоткрыть issue?

**Comment by Mishiranu** [comment]
Не недо переоткрывать. Надо создать новый.
