### ISSUE TITLE
Локальный архивач

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#72]
Можно сделать фичу "сохранять выбранные треды с определенным интервалом"?

**Comment by Mishiranu** [comment]
Нет, так не получится по многим причинам. Во-первых, дашчан в принципе сейчас в фоне не работает, какая либо работа с кэшом треда происходит только когда этот самый тред открыт перед глазами. Во-вторых, сохранение архитектурно спроектировано так, чтобы работать только когда пользователь запускает это архивирование. Как-то это автоматизировать будет сложно. Вряд ли это когда-либо будет сделано.

**Comment by ololoe** [comment]
Но обновление тредов работает, что мешает вместо проверки количества постов запускать архивирование?

**Comment by Mishiranu** [comment]
Обновление тредов не работает с кэшом, для него отдельное упрощённое хранилище.
По той же причине сейчас невозможно то, что ты [https://github.com/Mishiranu/Dashchan/issues/40#issuecomment-240827494](здесь) написал.

**Comment by ololoe** [comment]
А какая собсно разница? У тебя есть некое событие, запускаемое по таймеру.

**Comment by Mishiranu** [comment]
Разница в том, что трекер не работает с кэшом треда. А для архивирования нужно:

1. Достать тред из кэша
2. Загрузить новые посты для треда
3. Записать тред в кэш
4. Записать новый HTML файл треда для текущего кэша

Существенная разница, нужно довольно много всего продумать.

**Comment by ololoe** [comment]
Функция архивирования треда уже есть готовая о_О

**Comment by Mishiranu** [comment]
Так она архивирует открытый в данный момент тред, поэтому первые 3 пункта не нужны. А то что ты предлагаешь — это совершенно другое.

**Comment by ololoe** [comment]
У тебя есть 2 готовые функции которые нужно дернуть - обновление_треда и архивирование.

**Comment by Mishiranu** [comment]
Во-первых 4, во вторых их не получится "просто дёрнуть".
