### ISSUE TITLE
Автосохранение набранного текста

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#73]
Если набрать текст, переключиться на другое приложение, после этого из-за нехватки памяти прогу прибьют, то текст тоже пропадет.

**Comment by Mishiranu** [comment]
Он и так сохраняется. У тебя что-то не так в системе, раз это не работает.

**Comment by ololoe** [comment]
Давно сохраняется?

**Comment by Mishiranu** [comment]
Довольно давно. Если приложение убивается при нехватке памяти, то сохраняется ещё с первых версий дашчана, которые ещё в 2014 году выходили.

**Comment by ololoe** [comment]
При выходе через кнопку "назад" тоже сохраняется?

**Comment by Mishiranu** [comment]
Да, хотя конкретно это было сделано не так давно — месяца 4 назад где-то.

**Comment by ololoe** [comment]
На свежей версии работает, на той что была до этого сабж не работал и при нехватке памяти.
