### ISSUE TITLE
Снимать автообновление с удаленных/закрытых тредов

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#74]
Причина обновлять пропадает.

**Comment by Mishiranu** [comment]
Почему вручную не снимать?
Причём если с удалённым тредами ещё можно сделать, то с закрытыми уже всё не так просто. Как минимум, тред могут вновь открыть после закрытия. И вообще трекер не определяет, закрыт тред или нет.

**Comment by ololoe** [comment]
Кто такой трекер? У меня появляется крестик на боковой панели, это же значит закрыт?

Можно сделать опцией. Вручную - дополнительная работа.

**Comment by Mishiranu** [comment]
Трекер это "система отслеживания избранных тредов" для краткости. Крестик значит удалён.

**Comment by ololoe** [comment]
Значит, замечательно определяет.

Каким запросом проверяются обновления на дваче? Влом сниффер запускать.

**Comment by Mishiranu** [comment]
`http://2ch.hk/makaba/mobile.fcgi?task=get_thread_last_info&board=mobi&thread=846819`

**Comment by Mishiranu** [comment]
> Значит, замечательно определяет.

Как это? Если тред _закрыт_, то трекер это никак не отобразит. Отобразит только если _удалён_.

**Comment by ololoe** [comment]
А это реально быстрее чем запросить тред/обновления?

**Comment by Mishiranu** [comment]
В случае с мобильным трафиком и большими тредами — конечно. А если даже закрыть на это глаза, обработка данных тоже проще и быстрее.

Многие сайты не имеют подобного интерфейса, поэтому приходится грузить весь тред, однако обработка данных всё равно быстрее, когда не нужно парсить все посты, поэтому трекер работает отдельно.

**Comment by ololoe** [comment]
Ну да, определяет если удален. Для этого случая можно снимать обновление, хотя бы в качестве опции?

**Comment by Mishiranu** [comment]
Да, я подумаю насчёт этого.
