### ISSUE TITLE
Рефреш капчи после протухания

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#75]
Сраная макака поставила время жизни капчи 3 минуты, иногда пока пишешь пост она протухает. Хорошо бы ее в таком случае рефрешить.

**Comment by Mishiranu** [comment]
Не всегда есть возможность узнать, протухла капча или нет. На всех имиджбордах период разный.
Но над этим подумаю ещё.

**Comment by ololoe** [comment]
Меня интересует конкретно сосач, там время жизни капчи узнается через апи.

**Comment by ololoe** [comment]
https://2ch.hk/api/captcha/settings/b

**Comment by Mishiranu** [comment]
Я знаю.

**Comment by ololoe** [comment]
Для двача вопрос закрыт, как на других бордах - хз.

**Comment by Mishiranu** [comment]
А что с ним изменилось?

**Comment by ololoe** [comment]
Там капчу вводить не надо.
