### ISSUE TITLE
Проверка тредов заглючивает рутер

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#76]
Есть у меня подозрение, что от кучи одновременных проверок избранного у меня рутер начинает гадить коксом. Там для каждого запроса открывается новое соединение или как?

**Comment by Mishiranu** [comment]
Не понял, какой рутер и что значит гадить коксом?

Я не знаю, сколько он соединений там открывает, реализация HTTP-клиента осуществляется самой системой, причём эта самая реализация может отличаться в зависимости от версии устройства. Но скорее всего используется одно соединение, поскольку обновление происходит последовательно.

**Comment by ololoe** [comment]
Вот от быстрого открытия кучи соединений рутер может начинать глючить. Можно ли что-то с этим сделать, например, использовать keep-alive? :) Или проверять несколько тредов одним запросом для сосача.

**Comment by Mishiranu** [comment]
Я ещё раз говорю, это не от меня зависит, а от реализации клиента на стороне андроида. Наверное в 2016 году он использует keep-alive, так что обновления должны происходить на одном соединении. Чтобы точно определить, нужно уже смотреть через сниффер.

**Comment by ololoe** [comment]
Хттп клиент не твой что ли?

**Comment by Mishiranu** [comment]
Нет, не мой. Зачем использовать свой, если есть системный, и он вполне нормальный?

Пускай определяется прошивкой, умеет выполнять запросы и работать более-менее нормально — и хватит с него. Апи андроида тоже определяется прошивкой, знаешь ли.

**Comment by ololoe** [comment]
Я посмотрю что снифер покажет, но вообще-то не уметь keep-alive - это жопа, я тебе скажу.

**Comment by Mishiranu** [comment]
Сниффер показал, что используется одно соединение при работе одного лишь трекера, как и ожидалось. Сомневаюсь, что у тебя будет другой результат. В любом случае, если роутер начинает глючить из-за ната — проблема таки в роутере.
