### ISSUE TITLE
Опция: перенести скролл на другую сторону.

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#77]
Будет полезно для левшей.

**Comment by Mishiranu** [comment]
Скроллбар — системный элемент, он располагается только справа. К тому же слева уже находится дровер, только мешать друг другу будут.

**Comment by ololoe** [comment]
А то что его  можно перетаскивать - это тоже в системном есть, или таки кастомизация?

Выползающую хрень можно соотетственон направо перенести.

**Comment by Mishiranu** [comment]
Перетаскиваемый ползунок это тоже системная фича.

На самом деле, я не совсем прав, вполне возможно, что способ перенести скроллбар налево есть. Но так всё равно никто не делает, если бы это было нужно, в системе бы давно была опция "для левшей", которая автоматически перемещает все скроллбары влево экрана, как это сделано с RTL режимом в андроиде 4.2.

**Comment by ololoe** [comment]
Эта фича нужна именно для перетаскиваемого ползунка, т.к. листая большим пальцем правой руки, можно зацепить ползунок и нехило сбить скролл. А перетаскиваемый ползунок я имхо видел только в приложениях чанов.
