### ISSUE TITLE
Back out of image viewer by flicking/swiping up or down

### ISSUE THREAD

**Issue by ghost** [Mishiranu/Dashchan#8]
I love this feature in apps like Telegram and Fenix.

**Comment by Mishiranu** [comment]
I don't think it's necessary. There are 3 ways to close image: back button in navbar, arrow button in toolbar and tapping on free space out of image.

**Comment by GiRaFa-SM** [comment]
If you have root+xposed you can use the xposed module called SwipeBack. That app works to what you need.

**Comment by Mishiranu** [comment]
Added in last version.
