### ISSUE TITLE
Скрыть дерево - автоскрытие новых ответов

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#80]
1. Не скрываются новые ответы на скрытый коммент.
2. Как обрабатываются ответы на ответы?

**Comment by Mishiranu** [comment]
Автоскрытие гораздо сложнее, чем разовое скрытие дерева ответов. Уже предлагали, может когда-нибудь сделаю.

> Как обрабатываются ответы на ответы?

Скрываются, на то это и скрытие дерева ответов.

**Comment by ololoe** [comment]
>Автоскрытие гораздо сложнее, чем разовое скрытие дерева ответов.

Делаешь set из скрытых постов вместе с потомками. Для каждого из новых постов по порядку смотришь на что они ссылаются, если на посты из set-а - скрываешь пост и добавляешь его в set. Ничего сложного.
