### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#82]
Стоит показывать, за какое время (с какой даты) собрана статистика программы. Ну и до кучи количество сообщений в день или месяц итд. Опционально - статистика по месяцам.

**Comment by Mishiranu** [comment]
Идея хорошая, но я не знаю, как её теперь реализовывать, когда у многих статистика уже больше года копится. Надо было с самого начала это продумывать.

**Comment by ololoe** [comment]
Дату установки приложения можно получить? Нет - начинать считать отдельно со следующего апдейта.

**Comment by Mishiranu** [comment]
Ни так, ни так будет неправильно. Например, статистика велась не всегда, у некоторых датой установки может быть 2014 год, тогда как статистика появилась в 2015. Другой пример — человек мог установить приложение и восстановить старый бэкап. В любом случае, в результате имеем, что без полного обнуления статистики эта дата вообще не будет иметь никакого значения.

**Comment by ololoe** [comment]
Можно сделать статистику за все время работы или до апдейта и статистику после апдейта

**Comment by Mishiranu** [comment]
> Можно сделать статистику за все время работы

?

> до апдейта и статистику после апдейта

Ну это уже точно перебор.

**Comment by ololoe** [comment]
> Можно сделать статистику за все время работы

То и значит - статистику с момента установки программы.

>Ну это уже точно перебор.

Какие альтернативы? Сбросить всю статистику?

**Comment by Mishiranu** [comment]
> То и значит - статистику с момента установки программы.

Её ведь можно сбросить. Не вижу смысла в этом, это может быть полезно только тем, кто вот только сейчас её установил.

> Какие альтернативы? Сбросить всю статистику?

Вообще не делать, например. Хотя я ещё думал над тем, чтобы не показывать дату вообще, и начать делать это только после сброса.
