### ISSUE TITLE
[2ch] Настройки домена

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#84]
Если открыть настройки домена харкача - будут 3 выбора: hk, pm и другой. Если выбрать другой, то после следующего щелчка по этому пункту вместо выбора будет поле ввода. Если вернуться в предыдущее меню то все нормально.

**Comment by Mishiranu** [comment]
Всё нормально, так и задумано.

**Comment by ololoe** [comment]
И в чем прикол?

**Comment by Mishiranu** [comment]
В том, что после этого выбора настройка заменяется на текстовую. Допустим, если ты укажешь там что-то, то даже после выхода-входа она останется текстовым полем.
