### ISSUE TITLE
[2ch] Капча

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#85]
Куда делась капча? И почему она пропала именно сейчас?

**Comment by wildflypower** [comment]
Потому что двощи лежат уже третий день.

**Comment by ololoe** [comment]
Во-первых, двочи работают на pm домене, во-вторых, она исчезла до падения.

**Comment by Mishiranu** [comment]
"Обход капчи" в настройках модуля.

**Comment by ololoe** [comment]
Как он работает? Почему капча появилась, висела, а потом снова пропала?

**Comment by Mishiranu** [comment]
> Как он работает?

Особый тип капчи для мобильных устройств.

> Почему капча появилась, висела, а потом снова пропала?

Что?
