### ISSUE TITLE
Не открывать скачанные файлы из интернета

### ISSUE THREAD

**Issue by ololoe** [Mishiranu/Dashchan#86]
Если файл уже сохранялся - не грузить его из интернета при просмотре. По крайней мере, для скачанного треда не должно реализовываться сложно.

**Comment by Mishiranu** [comment]
С этим есть большие проблемы. Во-первых, теоретически можно что угодно класть в папку загрузок. Во-вторых, после сохранения имена могут не совпадать с именем на сайте по ряду причин. В некоторых, совсем частных случаях, это можно реализовать, но в общем случае — нет.

**Comment by ololoe** [comment]
В случае скачивания треда имхо все однозначно. 

>можно что угодно класть в папку загрузок
ССЗБ?

**Comment by Mishiranu** [comment]
> В случае скачивания треда имхо все однозначно.

Тоже не однозначно. Наример — на доброчане в одном треде могут быть картинки с одинаковыми названиями, но при этом быть разными.

> ССЗБ?

Просто общая свалка картинок со всех приложений на телефоне, как вариант.
