### ISSUE TITLE
4chan "Options" field support

### ISSUE THREAD

**Issue by Xyllon** [Mishiranu/Dashchan#87]
Hey,

Could you please add support for the "Options" field? It's useful now.

**Comment by Mishiranu** [comment]
And what does this field do now?

**Comment by Xyllon** [comment]
Typing "fortune" in /s4s/ will add a fun little footer to your post, typing "since4pass" on any board will add a footer showing how long you've had a 4chan pass for. Don't know of others.

**Comment by Mishiranu** [comment]
I can implement options field as email field, ok?

**Comment by Xyllon** [comment]
Yep. It's the same thing, just a different name.

**Comment by Mishiranu** [comment]
Added in new update.
