### ISSUE TITLE
8chan captcha "no need to enter captcha"

### ISSUE THREAD

**Issue by diyasteng** [Mishiranu/Dashchan#88]
8cha ext doesnt want me to enter captcha

**Comment by Mishiranu** [comment]
But it should? On what board?

**Comment by diyasteng** [comment]
Every board. i mean i havent typed the captcha yet and it says i dont need to enter the captcha

**Comment by Mishiranu** [comment]
On the most boards there are no capthca on 8chan. Some boards have it, and also there can be captcha when your IP in block list. In this case, when you send post from browser, you'll see a popup with captcha link. Are you talking about the rest type of captcha? It may be broken because it was implemented 1.5 years ago.

**Comment by Malvarose** [comment]
To help clear things up:

8chan has a global 24 hour captcha you must fill out to post.  Some boards have an additional captcha per post.  

What is actually wrong is that one of the admins changed how the global captcha worked.  It used to open in a new tab, you fill it out, and close the tab.  This was annoying, so now the captcha pops up on the page, you enter it in, and close it.

Now in Dashchan it just says "you do not need to enter a captcha", when you still need to enter the global catpcha, but it doesn't seem to know that.

@Mishiranu

**Comment by Mishiranu** [comment]
Ok, I've tried to fix a captcha. When you click on "send", you may see a popup window with captcha. It's more reliable than old way. Check it.

**Comment by Malvarose** [comment]
I can send now, which is awesome.  I had already filled out the captcha on my computer earlier, and since it is based on IP it didn't ask me to do it again.

I can update you on whether or not entering a captcha works.

**Comment by Malvarose** [comment]
Yeah, like I said it works fine if you had already entered the captcha somewhere else.  (like your computer)

But if you have not entered it at all that day, then the app does not prompt you to enter in the captcha.  It just gives me an "invalid server response", and tells me I do not need to enter a captcha.  (when I do)

@Mishiranu

**Comment by Mishiranu** [comment]
Create a `log` folder (https://github.com/Mishiranu/Dashchan/wiki/Home-EN#problem-solving), restart app and try to send post again. Then give me a log from this folder.

**Comment by diyasteng** [comment]
Device: samsung herolte (SM-G930F)
SDK: 23 (6.0.1)
Application: 1031 (2.8.3)
----------------------------------------
chan.content.InvalidResponseException
	at com.mishiranu.dashchan.chan.infinite.InfiniteChanPerformer.onSendPost(InfiniteChanPerformer.java:398)
	at chan.content.ChanPerformer$Safe.onSendPost(ChanPerformer.java:1338)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:173)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Mishiranu** [comment]
Ok. Now install this modified extension and make log again. [DashchanInfinite-debug.zip](https://github.com/Mishiranu/Dashchan/files/512594/DashchanInfinite-debug.zip)

It's an APK file, not ZIP, so rename it before installation! Github doesn't support APK file uploading.

**Comment by diyasteng** [comment]
08:52:31.552: "HTML response: {"captcha":true|"_m":"If you can see this, please copy and paste this link into your browser to complete the captcha for non-javascript users: https://8ch.net/dnsbls_bypass.php"}"
----------------------------------------
Device: samsung herolte (SM-G930F)
SDK: 23 (6.0.1)
Application: 1031 (2.8.3)
----------------------------------------
chan.content.InvalidResponseException
	at com.mishiranu.dashchan.chan.infinite.InfiniteChanPerformer.onSendPost(InfiniteChanPerformer.java:419)
	at chan.content.ChanPerformer$Safe.onSendPost(ChanPerformer.java:1338)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:173)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Mishiranu** [comment]
> `{"captcha":true|"_m":"`

Looks like 8chan JSON generator is broken.

Try this: [DashchanInfinite-debug.zip](https://github.com/Mishiranu/Dashchan/files/512667/DashchanInfinite-debug.zip)

**Comment by diyasteng** [comment]
its working now but i have to send a comment for the captcha window to pop up. thanks mishiranu!

**Comment by Mishiranu** [comment]
> i have to send a comment for the captcha window to pop up
Yes, this is the same behavior like on web browser: you send post, 8chan asks you about captcha, you open link and enter this captcha, then send post again. I'd prefer showing captcha before clicking "send" button, but there is no way to determine captcha necessity until you try to send post. I've had a little workaround for this before, but it didn't work for Tor users.
I'll release a new version with this fix soon.
