### ISSUE TITLE
Расширения для движков

### ISSUE THREAD

**Issue by kisleey** [Mishiranu/Dashchan#89]
Я вот тут подумал.

Существуют ведь множество борд, которые работают на одном и том же движке, практически без изменений. Почему бы не выпускать модули специально для этих движков вместо того, чтобы отдельно создавать идентичные модули для конкретных имиджборд? В настройки приложения можно добавить возможность добавления нужной АИБ с выбором движка.
Можно, конечно, менять адрес в настройках модулей, но это довольно муторно.

**Comment by Mishiranu** [comment]
У меня когда-то была идея сделать подобное, но несколько иначе. Я хотел сделать модули "клонируемыми": можно взять любой готовый модуль, через интерфейс приложения его "клонировать", сделав модулем для другого форума.

Но, некоторое время подумав, я решил, что это мёртвая идея. Если даже сейчас взглянуть на модули, полностью идентичных среди них нет: они все так или иначе чем-то отличаются. Движки часто модифицируют, движки бывают разных версий (взять тот же вичан, я замечал, что у него бывает разная структура апи), разные локали, разные часовые пояса, и так далее. Проблем просто куча и все их не покроешь универсальным кодом.

У меня даже "базовых классов" для модулей нет (вроде базового парсера для вакабы, кусабы и так далее), каждый модуль реализован с нуля исключительно по вышеописанной причине.

В общем, идея у меня в голове так-то есть давно, но я не уверен, что что-то подобное когда либо появится.
