### ISSUE TITLE
Pop-ups not closing

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#92]
When you click the bottom for replies, a pop-up shows up showing the replies. Sometimes this pop-up doesn't close. Not all the time.

May be related to the new update for mathjax?

**Comment by Mishiranu** [comment]
So, how does it look? You press back button but it doesn't close? What happens when you press multiple times?

> May be related to the new update for mathjax?

Definitely no.

**Comment by libeclipse** [comment]
It happens intermittently, but when it does happen that's pretty much how it is. Repeated presses of the back button navigate the page in the background back, but the overlay stays on top. Only a restart of the app appears to fix it.

The issue started after the mathjax update so it may be that. Also this morning my phone updated to Android 7.1.1 so that may be related, but I don't remember if I encountered the issue yesterday.

**Comment by Mishiranu** [comment]
> Also this morning my phone updated to Android 7.1.1 so that may be related, but I don't remember if I encountered the issue yesterday.

This is the most important I think. I'll try to test it on emulator.

**Comment by Mishiranu** [comment]
Open replies — close replies — open random image — close image.
After closing I see a dialog closed before. So I reproduced it.
It's a very strange Android issue. I'll try to fix it.

**Comment by sezycei** [comment]
Can confirm on a 7.1 device, this issue happens very frequently. Good luck getting it fixed!

**Comment by Mishiranu** [comment]
You'll have to wait until next version, I can't release a fix now.
