### ISSUE TITLE
Preload images

### ISSUE THREAD

**Issue by libeclipse** [Mishiranu/Dashchan#93]
When you're in /wg/ flicking through wallpapers, you have to wait for each one to load when you view it. This can add up to  substantial amounts of time - especially if the file sizes are in the megabytes and internet isn't the fastest.

When flicking through images or when loading a thread, you should actively load images ahead of what's being viewed. Either that or load the whole thread, but that's not really a nice solution.

**Comment by Mishiranu** [comment]
You can enable loading of nearest image in gallery in Settings — Contents — Load nearest image.

**Comment by libeclipse** [comment]
Oh nice. Loads of cool features hidden away.

**Comment by Mishiranu** [comment]
Have you tried to view all settings? Maybe you'll find something more.
