### ISSUE TITLE
Xynta.ch

### ISSUE THREAD

**Issue by kisleey** [Mishiranu/Dashchan#97]
Будьте добры, сделайте модуль для хуитача. Заранее спасибо.
На главной его странице ссылок на доски нет, если что. Надо вводить в адрес сразу доску (/b/, например.
И желательно, чтобы была реализована поддержка досок депрессариума (группы досок под адресом /d/, например, /d/a/).

**Comment by Mishiranu** [comment]
Готово. https://github.com/Mishiranu/Dashchan-Extensions/raw/master/update/package/DashchanXyntach.apk

**Comment by kisleey** [comment]
Дата у всех постов - 01.01.1970. И стоит добавить в список расширений в README.md.

**Comment by Mishiranu** [comment]
Совсем забыл сказать. С датами постов — временный баг. Это ошибка парсера в самом клиенте, которая была исправлена в https://github.com/Mishiranu/Dashchan/commit/dff6f065e9da47286172a658e9b859044ae58636, после его обновления всё станет нормально.

А ридми я забыл обновить, да.
